const names = [
	"Bitcoin",
	"Ethereum",
	"Tether",
	"XRP",
	"Bitcoin Cash",
	"Bitcoin SV",
	"Cardano",
	"Litecoin",
	"Binance Coin",
	"Crypto.com Coin",
	"Chainlink",
	"EOS",
	"Tezos",
	"Stellar",
	"TRON",
	"Monero",
	"UNUS SED LEO",
	"USD Coin",
	"VeChain",
	"Huobi Token",
	"Neo",
	"IOTA",
	"Ethereum Classic",
	"Cosmos",
	"Dash",
	"Zcash",
	"Maker",
	"Ontology",
	"NEM",
	"Aave",
	"Dogecoin",
	"HedgeTrade",
	"Compound",
	"Basic Attention Token",
	"Ampleforth",
	"OKB",
	"DigiByte",
	"Kyber Network",
	"Synthetix Network Token",
	"Dai",
	"FTX Token",
	"0x",
	"BitTorrent",
	"Augur",
	"Paxos Standard",
	"Algorand",
	"TrueUSD",
	"OMG Network",
	"Hyperion",
	"ICON",
	"Qtum",
	"THETA",
	"Elrond",
	"Hedera Hashgraph",
	"Zilliqa",
	"The Midas Touch Gold",
	"Decred",
	"Binance USD",
	"Bitcoin Diamond",
	"Bitcoin Gold",
	"Waves",
	"Lisk",
	"Enjin Coin",
	"Flexacoin",
	"Terra",
	"Swipe",
	"Ren",
	"DxChain Token",
	"Siacoin",
	"Ravencoin",
	"Nano",
	"Holo",
	"Loopring",
	"HUSD",
	"MonaCoin",
	"Nexo",
	"Divi",
	"Nervos Network",
	"Verge",
	"Bytom",
	"Quant",
	"ZB Token",
	"Aurora",
	"Celsius",
	"ABBC Coin",
	"Bancor",
	"Digitex Futures",
	"iExec RLC",
	"IOST",
	"Horizen",
	"Status",
	"Blockstack",
	"Band Protocol",
	"Kava",
	"Komodo",
	"Velas",
	"Matic Network",
	"Steem",
	"SwissBorg",
	"TomoChain",
	"BitShares",
	"KuCoin Shares",
	"Decentraland",
	"Hive",
	"WAX",
	"Reserve Rights",
	"MCO",
	"Aragon",
	"Zcoin",
	"aelf",
	"Stratis",
	"Ardor",
	"Energi",
	"Golem",
	"Syscoin",
	"Ocean Protocol",
	"Unibright",
	"HyperCash",
	"VeThor Token",
	"v.systems",
	"Electroneum",
	"Chiliz",
	"Ark",
	"Numeraire",
	"RSK Infrastructure Framework",
	"Aion",
	"Harmony",
	"Aeternity",
	"Super Zero Protocol",
	"PAX Gold",
	"Pundi X",
	"NULS",
	"Elastos",
	"Molecular Future",
	"MaidSafeCoin",
	"SOLVE",
	"Seele-N",
	"Travala.com",
	"Power Ledger",
	"WaykiChain",
	"IoTeX",
	"pNetwork",
	"Orbs",
	"CyberVein",
	"Wanchain",
	"IRISnet",
	"ReddCoin",
	"DAD",
	"Storj",
	"Fetch.ai",
	"Utrust",
	"Gatechain Token",
	"Kusama",
	"STASIS EURO",
	"Streamr",
	"Gnosis",
	"Loki",
	"XinFin Network",
	"Waltonchain",
	"Crypterium",
	"Ankr",
	"GXChain",
	"Cortex",
	"OriginTrail",
	"Fantom",
	"Theta Fuel",
	"Request",
	"Nimiq",
	"FunFair",
	"Thunder Token",
	"Ripio Credit Network",
	"Huobi Pool Token",
	"Voyager Token",
	"Beam",
	"Kleros",
	"TrueChain",
	"Fusion",
	"Dragonchain",
	"Wirex Token",
	"Haven Protocol",
	"Origin Protocol",
	"MXC",
	"BHEX Token",
	"WINk",
	"Celer Network",
	"PIVX",
	"Nebulas",
	"Insolar",
	"Project Pai",
	"MX Token",
	"Metal",
	"Loom Network",
	"COTI",
	"Enigma",
	"12Ships",
	"Chromia",
	"Function X",
	"Tachyon Protocol",
	"Mainframe",
	"Xensor",
	"HEX",
	"INO COIN",
	"Counos X",
	"Insight Chain",
	"BitcoinPoS",
	"VestChain",
	"TNC Coin",
	"Celo",
	"Zelwin",
	"MINDOL",
	"Largo Coin",
	"ThoreCoin",
	"MimbleWimbleCoin",
	"Tap",
	"Wrapped Bitcoin",
	"BeautyPayCoin",
	"botXcoin",
	"Idea Chain Coin",
	"Advanced Internet Blocks",
	"THORChain",
	"Metaverse Dualchain Network Architecture",
	"Homeros",
	"Baer Chain",
	"Sologenic",
	"Cryptonex",
	"yearn.finance",
	"Mixin",
	"Counos Coin",
	"Centrality",
	"ERC20",
	"QCash",
	"TerraKRW",
	"GlitzKoin",
	"NewYork Exchange",
	"Attila",
	"ThoreNext",
	"Beldex",
	"PlayFuel",
	"bZx Protocol",
	"Energy Web Token",
	"STEM CELL COIN",
	"Bitball Treasure",
	"Joule",
	"FABRK",
	"BTU Protocol",
	"Bitbook Gambling",
	"Vitae",
	"Poseidon Network",
	"Bytecoin",
	"ShareToken",
	"Bankera",
	"Orient Walt",
	"BitcoinHD",
	"IDEX",
	"Breezecoin",
	"Livepeer",
	"Karatgold Coin",
	"BitMax Token",
	"Buggyra Coin Zero",
	"DeviantCoin",
	"Rocket Pool",
	"Elamachain",
	"WhiteCoin",
	"Level01",
	"Handshake ",
	"Egoras",
	"Nectar",
	"Tratin",
	"USDK",
	"UNI COIN",
	"Stakenet",
	"Chimpion",
	"CasinoCoin",
	"PLATINCOIN",
	"Qubitica",
	"inSure",
	"AgaveCoin",
	"XeniosCoin",
	"Bloomzed Token",
	"Massnet",
	"Ultiledger",
	"RChain",
	"PRIZM",
	"Davinci Coin",
	"CRYPTO20",
	"sUSD",
	"BigONE Token",
	"Grin",
	"NEST Protocol",
	"NEXT",
	"Polymath",
	"Hellenic Coin",
	"Folgory Coin",
	"Civic",
	"Obyte",
	"8X8 PROTOCOL",
	"CRYPTOBUCKS",
	"WazirX",
	"Ecoreal Estate",
	"BOSAGORA",
	"Vid",
	"APIX",
	"Neutrino Dollar",
	"Everipedia",
	"ChainX",
	"WOM Protocol",
	"1irstcoin",
	"Quantstamp",
	"KardiaChain",
	"TrustSwap",
	"SingularityNET",
	"QuarkChain",
	"Populous",
	"StormX",
	"Envion",
	"Bluzelle",
	"Ignis",
	"NOIA Network",
	"ZEON",
	"Gas",
	"BitKan",
	"Dynamic Trading Rights",
	"Capricoin+",
	"AMO Coin",
	"V-ID",
	"Jewel",
	"Tellor",
	"Nash Exchange",
	"Cindicator",
	"GHOST",
	"Hxro",
	"Tierion",
	"CONTRACOIN",
	"Solana",
	"Constellation",
	"Switcheo",
	"Vertcoin",
	"ARPA Chain",
	"Uquid Coin",
	"LTO Network",
	"ExtStock Token",
	"Dent",
	"Atomic Wallet Coin",
	"SaluS",
	"JUST",
	"Akropolis ",
	"TROY",
	"Dusk Network",
	"Sport and Leisure",
	"CryptalDash",
	"Melon",
	"Lambda",
	"Raiden Network Token",
	"Darico Ecosystem Coin",
	"Groestlcoin",
	"Standard Tokenization Protocol",
	"Perlin",
	"ILCoin",
	"Nexus",
	"Elitium",
	"CONUN",
	"Contentos",
	"Minter Network",
	"WeShow Token",
	"GoChain",
	"Apollo Currency",
	"Invictus Hyperion Fund",
	"QASH",
	"Newton",
	"BHPCoin",
	"Bit-Z Token",
	"BORA",
	"Clams",
	"ZBG Token",
	"Aidos Kuneen",
	"Skycoin",
	"Kin",
	"BIKI",
	"IoT Chain",
	"Metaverse ETP",
	"Factom",
	"Wixlar",
	"VideoCoin",
	"Bread",
	"Cred",
	"TrustVerse",
	"Dero",
	"Monolith",
	"The Force Protocol",
	"HYCON",
	"Cocos-BCX",
	"MediBloc",
	"Orchid",
	"Grid+",
	"LBRY Credits",
	"Cryptoindex.com 100",
	"Aleph.im",
	"CyberMiles",
	"Unobtanium",
	"Gemini Dollar",
	"Aergo",
	"Bitcoin 2",
	"MovieBloc",
	"Proton",
	"Dragon Coins",
	"Carry",
	"PeepCoin",
	"TOP",
	"Game.com",
	"NKN",
	"Nxt",
	"AEN Smart Token",
	"Arcblock",
	"suterusu",
	"Einsteinium",
	"TTC",
	"FLETA",
	"Rakon",
	"Electra",
	"Ultra",
	"Spectre.ai Dividend Token",
	"Blocknet",
	"Emirex Token",
	"Nestree",
	"B2BX",
	"Dimension Chain",
	"Propy",
	"AirSwap",
	"Tael",
	"General Attention Currency",
	"REPO",
	"Metadium",
	"1SG",
	"Anchor",
	"HyperDAO",
	"ShipChain",
	"Telcoin",
	"MicroBitcoin",
	"FIBOS",
	"Mithril",
	"Neblio",
	"#MetaHash",
	"Cartesi",
	"LiquidApps",
	"Time New Bank",
	"AdEx",
	"Valor Token",
	"Meta",
	"LATOKEN",
	"DigixDAO",
	"BTSE",
	"NavCoin",
	"Burst",
	"TenX",
	"VITE",
	"Bonorum",
	"Prometeus",
	"MixMarvel",
	"Moeda Loyalty Points",
	"Santiment Network Token",
	"BitForex Token",
	"Veritaseum",
	"EveryCoin ",
	"TaaS",
	"CoinMetro Token",
	"OST",
	"DigitalBits",
	"King DAG",
	"Morpheus.Network",
	"Safe",
	"XMax",
	"Wings",
	"BASIC",
	"Ethereum Meta",
	"FirmaChain",
	"LCX",
	"Quantum Resistant Ledger",
	"DMarket",
	"Bibox Token",
	"DREP",
	"Content Value Network",
	"CWV Chain",
	"High Performance Blockchain",
	"VNX Exchange",
	"Gifto",
	"XYO",
	"Sentinel Protocol",
	"VIDY",
	"Dock",
	"Achain",
	"EDC Blockchain [old]",
	"Zenon",
	"DEAPcoin",
	"xDai",
	"PressOne",
	"SynchroBitcoin",
	"Blox",
	"DAOstack",
	"DDKoin",
	"Castweet",
	"Origo",
	"LinkEye",
	"Eminer",
	"Pillar",
	"Acute Angle Cloud",
	"Effect.AI",
	"CoinEx Token",
	"Polis",
	"Endor Protocol",
	"IQeon",
	"Po.et",
	"ODEM",
	"Titan Coin",
	"Everex",
	"Diamond Platform Token",
	"Digix Gold Token",
	"Cloudbric",
	"DOS Network",
	"ChronoCoin",
	"Dune Network",
	"Credits",
	"GameCredits",
	"ROOBEE",
	"Ravencoin Classic",
	"QuickX Protocol",
	"Peercoin",
	"Quark",
	"Moss Coin",
	"Sentivate",
	"YOU COIN",
	"FirstBlood",
	"PlayChip",
	"Ruff",
	"Genesis Vision",
	"SingularDTV",
	"SALT",
	"LINA",
	"Pluton",
	"FNB Protocol",
	"WePower",
	"Bezant",
	"Levolution",
	"All Sports",
	"IONChain",
	"Particl",
	"BnkToTheFuture",
	"Kcash",
	"Metronome",
	"IZE",
	"Monero Classic",
	"Morpheus Labs",
	"QLC Chain",
	"Ferrum Network",
	"Steem Dollars",
	"StakeCubeCoin",
	"Namecoin",
	"YOYOW",
	"HorusPay",
	"DAPS Coin",
	"Atlas Protocol",
	"Wagerr",
	"MOAC",
	"Safe Haven",
	"district0x",
	"S4FE",
	"TAGZ5",
	"Peculium",
	"EDUCare",
	"United Traders Token",
	"XIO",
	"Robotina",
	"SIRIN LABS Token",
	"Mooncoin",
	"USDQ",
	"Tokenomy",
	"Zano",
	"OAX",
	"Egretia",
	"Hydro Protocol",
	"Realio Network",
	"UGAS",
	"OTOCASH",
	"Insights Network",
	"Asch",
	"Pirate Chain",
	"Neumark",
	"FOAM",
	"GreenPower",
	"UnlimitedIP",
	"U Network",
	"Aeon",
	"ProximaX",
	"VIBE",
	"AppCoins",
	"GHOSTPRISM",
	"POA",
	"Lightning Bitcoin",
	"SmartMesh",
	"Compound Coin",
	"Clipper Coin",
	"SoMee.Social",
	"CryptoFranc",
	"Howdoo",
	"Cosmo Coin",
	"Selfkey",
	"Budbo",
	"Revain",
	"Covesting",
	"NPCoin",
	"Ergo",
	"Telos",
	"SmartCash",
	"Universa",
	"Viacoin",
	"HitChain",
	"TE-FOOD",
	"Jibrel Network",
	"SonoCoin",
	"qiibee",
	"BackPacker Coin",
	"Digital Asset Guarantee Token",
	"TokenClub",
	"INT Chain",
	"GAPS",
	"Measurable Data Token",
	"Phore",
	"Zel",
	"Leverj",
	"GeoDB",
	"Nexty",
	"OceanEx Token",
	"0Chain",
	"Ubiq",
	"SwftCoin",
	"LockTrip",
	"Aladdin",
	"Global Cryptocurrency",
	"ALQO",
	"Zap",
	"T.OS",
	"CEEK VR",
	"Bitrue Coin",
	"VNDC",
	"bitCNY",
	"Bitcoin Rhodium",
	"Safex Token",
	"smARTOFGIVING",
	"SunContract",
	"Sense",
	"Agrello",
	"Darwinia Network",
	"BLOCKv",
	"Metrix Coin",
	"Phantasma",
	"CanYaCoin",
	"USDJ",
	"Gulden",
	"Monetha",
	"GNY",
	"BitTube",
	"DigitalNote",
	"SONM",
	"XTRABYTES",
	"MediShares",
	"Ternio",
	"SIX",
	"KARMA",
	"FLO",
	"Observer",
	"Global Digital Content",
	"Viberate",
	"Red Pulse Phoenix",
	"BABB",
	"Vexanium",
	"Lykke",
	"Cashaa",
	"Spiking",
	"MultiVAC",
	"Agrocoin",
	"Newscrypto",
	"MIR COIN",
	"SymVerse",
	"Auctus",
	"Bitcore",
	"Doc.com Token",
	"Flash",
	"Dawn Protocol",
	"BitCapitalVendor",
	"ZrCoin",
	"Tripio",
	"Lamden",
	"DATA",
	"Ondori",
	"NIX",
	"AmonD",
	"Tokoin",
	"Verasity",
	"JD Coin",
	"Etheroll",
	"Global Social Chain",
	"Hi Mutual Society",
	"GET Protocol",
	"OneRoot Network",
	"Waves Enterprise",
	"Precium",
	"Sentinel",
	"GoCrypto Token",
	"EURBASE",
	"Everus",
	"Polybius",
	"Incent",
	"DeepBrain Chain",
	"BitGreen",
	"CUTcoin",
	"Matrix AI Network",
	"HTMLCOIN",
	"Dentacoin",
	"Genaro Network",
	"Odyssey",
	"QunQun",
	"THEKEY",
	"Blockmason Credit Protocol",
	"MVL",
	"Plair",
	"Jarvis Network",
	"BlackCoin",
	"PumaPay",
	"Hydro",
	"Mysterium",
	"ZIMBOCASH",
	"Kryll",
	"PCHAIN",
	"BOX Token",
	"Edge",
	"Cryptocean",
	"VeriBlock",
	"Credo",
	"CoTrader",
	"ContentBox",
	"VeriDocGlobal",
	"Nyzo",
	"VNT Chain",
	"Nucleus Vision",
	"Tidex Token",
	"Litecoin Cash",
	"Xaurum",
	"VINchain",
	"PegNet",
	"Hubii Network",
	"TrueFlip",
	"Bloom",
	"Raven Protocol",
	"Rupiah Token",
	"Emercoin",
	"BitMart Token",
	"CanonChain",
	"BaaSid",
	"LINKA",
	"Counterparty",
	"Kambria",
	"EOSDT",
	"CommerceBlock",
	"Color Platform",
	"OneLedger",
	"GridCoin",
	"Constant",
	"Vipstar Coin",
	"Naka Bodhi Token",
	"OKCash",
	"EOS Force",
	"PolySwarm",
	"USDx stablecoin",
	"Hiveterminal Token",
	"YEE",
	"Presearch",
	"DECOIN",
	"BOLT",
	"NAGA",
	"TERA",
	"Cajutel",
	"Futurepia",
	"RSK Smart Bitcoin",
	"ColossusXT",
	"Casino Betting Coin",
	"NaPoleonX",
	"Feathercoin",
	"PlatonCoin",
	"MintCoin",
	"Pivot Token",
	"Hashgard",
	"Litex",
	"Content Neutrality Network",
	"Lympo",
	"Lition",
	"Cryptopay",
	"Themis",
	"Esportbits",
	"ECC",
	"Peerplays",
	"Aryacoin",
	"Blackmoon",
	"WPP TOKEN",
	"nOS",
	"Refereum",
	"Spendcoin",
	"Scry.info",
	"Spectrecoin",
	"Mobius",
	"Myriad",
	"pEOS",
	"Skrumble Network",
	"LNX Protocol",
	"MESEFA",
	"Nasdacoin",
	"CargoX",
	"apM Coin",
	"Adshares",
	"Cardstack",
	"Ixcoin",
	"ProChain",
	"Cube",
	"EXMO Coin",
	"DAEX",
	"carVertical",
	"Airbloc",
	"Loopring [NEO]",
	"Winding Tree",
	"Maincoin",
	"Nuggets",
	"Callisto Network",
	"AMLT",
	"Apex",
	"INLOCK",
	"WeOwn",
	"Sharder",
	"Rotharium",
	"BidiPass",
	"Ambrosus",
	"Credit Tag Chain",
	"Wowbit",
	"Trias",
	"Abyss Token",
	"Swarm",
	"HoryouToken",
	"Penta",
	"Unikoin Gold",
	"Spectre.ai Utility Token",
	"Zipper",
	"Rublix",
	"Caspian",
	"Blue Whale EXchange",
	"Midas",
	"Isiklar Coin",
	"Era Swap",
	"Flowchain",
	"Cryptaur",
	"BIZZCOIN",
	"Pundi X NEM",
	"Humanscape",
	"Stealth",
	"Mcashchain",
	"Artfinity",
	"Beaxy",
	"Sparkpoint",
	"SyncFab",
	"Pascal",
	"SINOVATE",
	"Radium",
	"BetProtocol",
	"NuBits",
	"Infinitecoin",
	"IntelliShare",
	"Sakura Bloom",
	"Teloscoin",
	"ChatCoin",
	"Eterbase Coin",
	"Fatcoin",
	"Gleec",
	"Origin Sport",
	"Tixl",
	"ZClassic",
	"Terracoin",
	"PotCoin",
	"1World",
	"PAC Global",
	"Primas",
	"Crown",
	"Liquidity Network",
	"Unification",
	"BOScoin",
	"PayBX",
	"Enecuum",
	"bitUSD",
	"eBitcoin",
	"Snetwork",
	"Kuai Token",
	"X8X Token",
	"DEX",
	"GoWithMi",
	"Blockchain Certified Data Token",
	"Sumokoin",
	"Change",
	"Yap Stone",
	"BlockStamp",
	"DAOBet",
	"Opacity",
	"HOMIHELP",
	"UCA Coin",
	"PIBBLE",
	"Restart Energy MWAT",
	"PUBLISH",
	"TokenPay",
	"QChi",
	"Fast Access Blockchain",
	"Xaya",
	"NativeCoin",
	"CoinDeal Token",
	"ZumCoin",
	"Krios",
	"LikeCoin",
	"PLANET",
	"FansTime",
	"Open Platform",
	"Tolar",
	"Vetri",
	"SnowGem",
	"Bean Cash",
	"ROAD",
	"iEthereum",
	"Colu Local Network",
	"Amoveo",
	"Bottos",
	"IHT Real Estate Protocol",
	"Pandacoin",
	"REAL",
	"MenaPay",
	"I/O Coin",
	"Chrono.tech",
	"e-Gulden",
	"Aeron",
	"Dether",
	"Boolberry",
	"Denarius",
	"Databroker",
	"Sapien",
	"TRONCLASSIC",
	"indaHash",
	"NewYorkCoin",
	"Minereum",
	"X-CASH",
	"Banca",
	"BOOM",
	"EXRNchain",
	"Bitcoin Atom",
	"Diamond",
	"Bidesk",
	"Netbox Coin",
	"Ink Protocol",
	"NANJCOIN",
	"Curecoin",
	"Paypex",
	"SpaceChain",
	"ATC Coin",
	"Remme",
	"Education Ecosystem",
	"Veil",
	"Tokenbox",
	"Coineal Token",
	"Primecoin",
	"Smartlands",
	"VeriCoin",
	"Substratum",
	"Stronghold Token",
	"Flixxo",
	"Hashshare",
	"CoinPoker",
	"Rubycoin",
	"TurtleCoin",
	"SpankChain",
	"NuShares",
	"Dinastycoin",
	"QuadrantProtocol",
	"42-coin",
	"SafeCoin",
	"Eden",
	"Fountain",
	"RealTract",
	"Footballcoin",
	"Azbit",
	"AI Doctor",
	"MarketPeak",
	"AIDUS TOKEN",
	"Zenswap Network Token",
	"Axe",
	"Datum",
	"TEMCO",
	"Blockport",
	"Gene Source Code Chain",
	"Etherparty",
	"ZPER",
	"Aventus",
	"UNIVERSAL CASH",
	"CryptoVerificationCoin",
	"Brickblock",
	"ParkinGo",
	"Lunes",
	"Bismuth",
	"Cappasity",
	"Rapids",
	"ZelaaPayAE",
	"Trade Token X",
	"WinCash",
	"MEET.ONE",
	"Bitcoin Confidential",
	"Datamine",
	"BOMB",
	"Lendingblock",
	"CPChain",
	"EncrypGen",
	"IG Gold",
	"Banano",
	"Epic Cash",
	"Okschain",
	"Rise",
	"MonetaryUnit",
	"PetroDollar",
	"EUNO",
	"Swace",
	"eosDAC",
	"adbank",
	"Streamity",
	"Omni",
	"ATLANT",
	"Ubex",
	"Edgeless",
	"Medicalchain",
	"OracleChain",
	"Jobchain",
	"NoLimitCoin",
	"Cryptobuyer",
	"Bitex Global XBX Coin",
	"DomRaider",
	"BitNewChain",
	"HyperExchange",
	"Scala",
	"Ivy",
	"MalwareChain",
	"FREE Coin",
	"Conceal",
	"DreamTeam Token",
	"Lunyr",
	"DeepOnion",
	"Nework",
	"Zero",
	"Block-Chain.com",
	"Noku",
	"PayPie",
	"Mindexcoin",
	"ToaCoin",
	"Merculet",
	"Humaniq",
	"2key.network",
	"Dynamic",
	"CloakCoin",
	"FNKOS",
	"Bitswift",
	"ADAMANT Messenger",
	"Matryx",
	"Dovu",
	"NEXT.coin",
	"BonusCloud",
	"COVA",
	"Dimecoin",
	"0xBitcoin",
	"Wownero",
	"Delphy",
	"Expanse",
	"wave edu coin",
	"LUKSO",
	"Neurotoken",
	"Auroracoin",
	"MB8 Coin",
	"EchoLink",
	"Traceability Chain",
	"BQT",
	"Experty",
	"Digital Gold",
	"MargiX",
	"Zebi Token",
	"Sessia",
	"Amon",
	"STK",
	"YGGDRASH",
	"HalalChain",
	"RedFOX Labs",
	"BitcoinZ",
	"Xriba",
	"MobileGo",
	"Switch",
	"Debitum",
	"Ormeus Coin",
	"Ecobit",
	"LHT",
	"Beetle Coin",
	"FintruX Network",
	"Pigeoncoin",
	"Pirl",
	"Membrana",
	"GeoCoin",
	"Nexxo",
	"StableUSD",
	"ZeuxCoin",
	"NeoWorld Cash",
	"Asian Fintech",
	"Internxt",
	"SHIELD",
	"Sentient Coin",
	"KickToken",
	"Uptrennd",
	"Qwertycoin",
	"Moneytoken",
	"EXMR FDN",
	"Trollcoin",
	"ICNQ Token",
	"Bitsdaq",
	"Shift",
	"MARK.SPACE",
	"Blocktrade Token",
	"HashBX ",
	"Auxilium",
	"POPCHAIN",
	"Rate3",
	"Electronic Energy Coin",
	"ZENZO",
	"0xcert",
	"Solaris",
	"CannabisCoin",
	"SolarCoin",
	"Upfiring",
	"Pinkcoin",
	"AtromG8",
	"NOW Token",
	"PANTHEON X",
	"WeTrust",
	"SBank",
	"USDX",
	"Karbo",
	"Snovian.Space",
	"Coinsbit Token",
	"DecentBet",
	"GAMB",
	"Shivom",
	"Mercury",
	"SafeInsure",
	"Ether Zero",
	"Sphere",
	"Honest",
	"Halo Platform",
	"BitScreener Token",
	"Waves Community Token",
	"MineBee",
	"Nebula AI",
	"Ink",
	"FuzeX",
	"FYDcoin",
	"Blockparty (BOXX Token)",
	"Q DAO Governance token v1.0",
	"Faceter",
	"Espers",
	"Business Credit Substitute",
	"Phoenixcoin",
	"Devery",
	"HEAT",
	"Patientory",
	"TouchCon",
	"Bitcoin Plus",
	"Project WITH",
	"Coinsuper Ecosystem Network",
	"GoldMint",
	"Hush",
	"Pylon Network",
	"Bitcoin Private",
	"Mallcoin",
	"ESBC",
	"Insureum",
	"Rivetz",
	"MidasProtocol",
	"Bitblocks",
	"Fortuna",
	"VegaWallet Token",
	"Trinity Network Credit",
	"Merebel",
	"AICHAIN",
	"Skychain",
	"SafeCapital",
	"Stox",
	"OVCODE",
	"Niobium Coin",
	"MIB Coin",
	"Olive",
	"ATN",
	"Alphacat",
	"Playkey",
	"Semux",
	"EverGreenCoin",
	"Lobstex",
	"Arbidex",
	"TraDove B2BCoin",
	"LUXCoin",
	"SmileyCoin",
	"AMATEN",
	"Bob's Repair",
	"WinStars.live",
	"DATx",
	"Birake",
	"IQ.cash",
	"DEEX",
	"TurtleNetwork",
	"PIXEL",
	"Cashbery Coin",
	"TCASH",
	"Crypto Sports",
	"Novacoin",
	"Zippie",
	"ImageCoin",
	"ATMChain",
	"StrongHands",
	"PlayCoin [ERC20]",
	"Hacken Token",
	"Proton Token",
	"CoinFi",
	"CVCoin",
	"Zen Protocol",
	"Bitcoin Free Cash",
	"Orbitcoin",
	"WebDollar",
	"Evedo",
	"NeuroChain",
	"RED",
	"CACHE Gold",
	"BitCash",
	"GMB",
	"BitCrystals",
	"TEAM (TokenStars)",
	"Electrify.Asia",
	"HiCoin",
	"Vodi X",
	"DPRating",
	"Graviocoin",
	"Sociall",
	"SIBCoin",
	"HEROcoin",
	"Zeepin",
	"ODUWA",
	"Eureka Coin",
	"SPINDLE",
	"Infinitus Token",
	"GlobalBoost-Y",
	"Quiztok",
	"LocalCoinSwap",
	"Sentinel Chain",
	"HOLD",
	"DECENT",
	"Trittium",
	"Smartshare",
	"EurocoinToken",
	"BUZZCoin",
	"Safex Cash",
	"Parachute",
	"Egoras Dollar",
	"Winco",
	"OLXA",
	"Patron",
	"HashCoin",
	"uPlexa",
	"The ChampCoin",
	"IDEX Membership",
	"BiblePay",
	"ZVCHAIN",
	"Golos Blockchain",
	"Eristica",
	"ICE ROCK MINING",
	"Jarvis+",
	"MEXC Token",
	"CryptoCarbon",
	"Playgroundz",
	"FedoraCoin",
	"AiLink Token",
	"ION",
	"FortKnoxster",
	"FLIP",
	"Starbase",
	"Vites",
	"AceD",
	"TigerCash",
	"Monarch",
	"Master Contract Token",
	"Proxeus",
	"MyWish",
	"DACSEE",
	"VouchForMe",
	"EBCoin",
	"Ulord",
	"Memetic / PepeCoin",
	"XEL",
	"Shadow Token",
	"Zeitcoin",
	"View",
	"On.Live",
	"Martkist",
	"VeriSafe",
	"PTON",
	"BitBall",
	"Maximine Coin",
	"VeriumReserve",
	"Raise",
	"Earneo",
	"Bridge Protocol",
	"HOQU",
	"adToken",
	"Essentia",
	"Ties.DB",
	"Bittwatt",
	"TV-TWO",
	"Rapidz",
	"AidCoin",
	"PHI Token",
	"Qredit",
	"BitDegree",
	"Paytomat",
	"Qbao",
	"CryCash",
	"Scorum Coins",
	"ExclusiveCoin",
	"imbrex",
	"Lisk Machine Learning",
	"XcelToken Plus",
	"SpectrumCash",
	"Maecenas",
	"Blue Protocol",
	"SwiftCash",
	"Internet of People",
	"Megacoin",
	"Social Send",
	"Alchemint Standards",
	"Max Property Group",
	"Typerium",
	"HempCoin",
	"EncryptoTel [WAVES]",
	"JET8",
	"OWNDATA",
	"Swarm City",
	"Noir",
	"Swap",
	"PAYCENT",
	"HUNT",
	"XPA",
	"Maverick Chain",
	"Vether",
	"CoinUs",
	"Opus",
	"Datawallet",
	"TOKPIE",
	"CREDIT",
	"Manna",
	"BetterBetting",
	"FujiCoin",
	"Giant",
	"GoNetwork",
	"Zilla",
	"Digital Insurance Token",
	"Bancacy",
	"DogeCash",
	"TrueFeedBack",
	"TrezarCoin",
	"DAV Coin",
	"EnergiToken",
	"Friendz",
	"eXPerience Chain",
	"Helix",
	"PiplCoin",
	"Ethereum Gold",
	"Block-Logic",
	"Baz Token",
	"BeatzCoin",
	"Motocoin",
	"KuboCoin",
	"DopeCoin",
	"Zeusshield",
	"BioCoin",
	"FlypMe",
	"savedroid",
	"IXT",
	"Webflix Token",
	"Jetcoin",
	"EventChain",
	"Neutron",
	"InflationCoin",
	"StarCoin",
	"Pakcoin",
	"Actinium",
	"Crowd Machine",
	"Decentralized Machine Learning",
	"CryptoPing",
	"Leadcoin",
	"Aston",
	"Graft",
	"Bounty0x",
	"Privatix",
	"Ryo Currency",
	"Coinlancer",
	"KekCoin",
	"Celeum",
	"GoByte",
	"DABANKING",
	"Bitnation",
	"Masari",
	"MyBit",
	"HelloGold",
	"DIMCOIN",
	"BZEdge",
	"DubaiCoin",
	"Cubiex",
	"Ultimate Secure Cash",
	"Nerva",
	"TrueDeck",
	"ZMINE",
	"Omnitude",
	"AllSafe",
	"Thrive Token",
	"Alpha Token",
	"Bitzeny",
	"DeVault",
	"UpToken",
	"BoutsPro",
	"Primalbase Token",
	"Equal",
	"x42 Protocol",
	"Ouroboros",
	"AudioCoin",
	"LiteDoge",
	"Utrum",
	"Monkey Project",
	"CaixaPay",
	"FSBT API Token",
	"IP Exchange",
	"BlitzPredict",
	"LanaCoin",
	"Indorse Token",
	"Scanetchain",
	"Moneynet",
	"MetaMorph",
	"Bigbom",
	"Bethereum",
	"eBoost",
	"Gems ",
	"Adelphoi",
	"eSDChain",
	"WandX",
	"InvestDigital",
	"GoldFund",
	"ArdCoin",
	"Blockpass",
	"Dropil",
	"Helium Chain",
	"Bitsum",
	"Startcoin",
	"Cobinhood",
	"ZUM TOKEN",
	"Goldcoin",
	"Emerald Crypto",
	"Amino Network",
	"Bezop",
	"PEPS Coin",
	"Ritocoin",
	"Signals Network",
	"Carboneum [C8] Token",
	"Lethean",
	"Energycoin",
	"Ubricoin",
	"GravityCoin",
	"MMOCoin",
	"Profile Utility Token",
	"Peony",
	"Silent Notary",
	"Freicoin",
	"PengolinCoin",
	"Bolivarcoin",
	"Energo",
	"Ignition",
	"Sharpay",
	"FarmaTrust",
	"RealChain",
	"SignatureChain ",
	"Alt.Estate token",
	"Maxcoin",
	"Bitcoin Incognito",
	"WOLLO",
	"iDealCash",
	"Matchpool",
	"Kuende",
	"MesChain",
	"OptiToken",
	"Gravity",
	"W Green Pay",
	"EvenCoin",
	"Matrexcoin",
	"Ether-1",
	"Relex",
	"Bitcoin Token",
	"SWYFT",
	"The Currency Analytics",
	"Chronologic",
	"Swing",
	"Transcodium",
	"Version",
	"Quasarcoin",
	"bitEUR",
	"ZCore",
	"Catex Token",
	"LIFE",
	"Coin Lion",
	"Bitcoin CZ",
	"LOCIcoin",
	"MktCoin",
	"Limitless VIP",
	"WIZBL",
	"NetKoin",
	"Truegame",
	"MTC Mesh Network",
	"Kuverit",
	"Menlo One",
	"HYPNOXYS",
	"EtherSportz",
	"Verify",
	"BlueCoin",
	"OSA Token",
	"Universe",
	"OBITS",
	"Arionum",
	"Gentarium",
	"MFCoin",
	"Pesetacoin",
	"BoatPilot Token",
	"FirstCoin",
	"Emphy",
	"Storiqa",
	"TENA",
	"StarterCoin",
	"Synergy",
	"Oxycoin",
	"Zennies",
	"ebakus",
	"Birdchain",
	"Artis Turba",
	"Hyper Speed Network",
	"Litecoin Plus",
	"PWR Coin",
	"CROAT",
	"ONOToken",
	"CryptoBonusMiles",
	"AC3",
	"BitClave",
	"CryptoAds Marketplace",
	"BitSend",
	"ZINC",
	"Eroscoin",
	"BBSCoin",
	"HeartBout",
	"BitBar",
	"BEAT",
	"Veles",
	"MAX Exchange Token",
	"Bonpay",
	"Business Credit Alliance Chain",
	"Veros",
	"Blur",
	"PAL Network",
	"Rentberry",
	"InsaneCoin",
	"SRCOIN",
	"Kalkulus",
	"Bitstar",
	"Bitcloud",
	"MorCrypto Coin",
	"Gossip Coin",
	"XDNA",
	"Carboncoin",
	"Unify",
	"HeroNode",
	"Kobocoin",
	"Anoncoin",
	"Webcoin",
	"Vanta Network",
	"Yocoin",
	"TrumpCoin",
	"Grimm",
	"StrongHands Masternode",
	"MicroMoney",
	"Elementeum",
	"Bata",
	"Elcoin",
	"Bitcoin Interest",
	"PENG",
	"Naviaddress",
	"Garlicoin",
	"Rupee",
	"Thore Cash",
	"EtherGem",
	"KZ Cash",
	"HashNet BitEco",
	"Cashpayz Token",
	"InvestFeed",
	"QUINADS",
	"Innovative Bioresearch Classic",
	"Vidulum",
	"Bitradio",
	"Zetacoin",
	"PLAAS FARMERS TOKEN",
	"Fire Lotto",
	"SiaCashCoin",
	"PoSW Coin",
	"Swapcoinz",
	"Cryptonite",
	"Seal Network",
	"CryptoSoul",
	"InterValue",
	"vSlice",
	"Ethereum Gold Project",
	"Atonomi",
	"Opal",
	"LEOcoin",
	"Dynamite",
	"XGOX",
	"Ifoods Chain",
	"Bitfex",
	"SophiaTX",
	"Suretly",
	"TajCoin",
	"Paragon",
	"ACE (TokenStars)",
	"MODEL-X-coin",
	"Plus-Coin",
	"PYRO Network",
	"Photon",
	"Deutsche eMark",
	"ParallelCoin",
	"Bee Token",
	"BlockCAT",
	"PlayGame",
	"Fox Trading",
	"bitBTC",
	"NFX Coin",
	"Ethersocial",
	"AdHive",
	"Aditus",
	"Fiii",
	"Neutral Dollar ",
	"Paymon",
	"Bitcoin Red",
	"CyberFM",
	"Ethereum Cash",
	"Rimbit",
	"CrypticCoin",
	"Pyrk",
	"ANON",
	"Apollon",
	"TransferCoin",
	"Daneel",
	"Blockburn",
	"RoBET",
	"Taklimakan Network",
	"Voise",
	"KanadeCoin",
	"Netko",
	"LALA World",
	"TOKYO",
	"Kurrent",
	"TagCoin",
	"CYCLEAN",
	"Hurify",
	"Global Currency Reserve",
	"Digitalcoin",
	"Bitether",
	"GlobalToken",
	"Guaranteed Ethurance Token Extra",
	"INMAX",
	"Evil Coin",
	"Asian Dragon",
	"Elysian",
	"CaluraCoin",
	"2GIVE",
	"MultiCoinCasino",
	"BitStation",
	"SkinCoin",
	"ProxyNode",
	"Social Activity Token",
	"Civitas",
	"SuperCoin",
	"Italian Lira",
	"SounDAC",
	"Iridium",
	"PRASM",
	"OPCoinX",
	"RightMesh",
	"AquariusCoin",
	"Ultragate",
	"BitWhite",
	"VULCANO",
	"Commercium",
	"ImageCash",
	"Doge Token",
	"HyperQuant",
	"Streamit Coin",
	"Kind Ads Token",
	"Mainstream For The Underground",
	"TrueVett",
	"PluraCoin",
	"Parkgene",
	"Innovative Bioresearch Coin",
	"Helex",
	"SelfSell",
	"GCN Coin",
	"Narrative",
	"BitRewards",
	"Bela",
	"DraftCoin",
	"Regalcoin",
	"SONDER",
	"PDATA",
	"Bitgesell",
	"EtherInc",
	"BitCoen",
	"Bitcoin Zero",
	"Impleum",
	"BTC Lite",
	"No BS Crypto",
	"Niobio Cash",
	"BlockMesh",
	"Stellar Classic",
	"XMCT",
	"Thar Token",
	"UChain",
	"CommunityGeneration",
	"Autonio",
	"PUBLYTO Token",
	"Bitcoin Fast",
	"DOWCOIN",
	"Cryptojacks",
	"KAASO",
	"CrowdWiz",
	"Cheesecoin",
	"Freyrchain",
	"WABnetwork",
	"Thingschain",
	"Knekted",
	"Arqma",
	"Adzcoin",
	"Micromines",
	"Joint Ventures",
	"Xuez",
	"Universal Currency",
	"Arion",
	"Advanced Technology Coin",
	"ChessCoin",
	"Klimatas",
	"FantasyGold",
	"Agrolot",
	"BLOC.MONEY",
	"ATBCoin",
	"GoldenPyrex",
	"Mobile Crypto Pay Coin",
	"IFX24",
	"Moin",
	"SteepCoin",
	"PopularCoin",
	"PureVidz",
	"Blocklancer",
	"AirWire",
	"CDX Network",
	"TRAXIA",
	"Worldcore",
	"BLAST",
	"iTicoin",
	"ZeusNetwork",
	"FUZE Token",
	"EthereumX",
	"Ethouse",
	"STRAKS",
	"PRiVCY",
	"Eternity",
	"UNICORN Token",
	"IGToken",
	"SnodeCoin",
	"ClearPoll",
	"Exosis",
	"Aigang",
	"Arepacoin",
	"Guider",
	"EDRCoin",
	"APR Coin",
	"SCRIV NETWORK",
	"VoteCoin",
	"Herbalist Token",
	"Theresa May Coin",
	"InternationalCryptoX",
	"More Coin",
	"Linfinity",
	"ETHplode",
	"CYBR Token",
	"bitGold",
	"GuccioneCoin",
	"Cream",
	"Intelligent Trading Foundation",
	"Digiwage",
	"Italo",
	"MojoCoin",
	"Datarius Credit",
	"Rubies",
	"Blocktix",
	"Abitshadow Token",
	"Coinchase Token",
	"DeltaChain",
	"Payfair",
	"ELTCOIN",
	"Aricoin",
	"EZOOW",
	"Ellaism",
	"Galilel",
	"Bitcoiin",
	"Diligence",
	"Biotron",
	"Authorship",
	"Netrum",
	"SmartCoin",
	"CFun",
	"Cryptrust",
	"Agora",
	"Octoin Coin",
	"MESG",
	"BitStash",
	"ShowHand",
	"xEURO",
	"JSECOIN",
	"BitcoiNote",
	"EveriToken",
	"Jade Currency",
	"YENTEN",
	"GoHelpFund",
	"SHPING",
	"RefToken",
	"BERNcash",
	"Neural Protocol",
	"BitRent",
	"YoloCash",
	"BitNautic Token",
	"Provoco Token",
	"Acoin",
	"Citadel",
	"EUNOMIA",
	"Waletoken",
	"GeyserCoin",
	"Asura Coin",
	"Connect Coin",
	"Tourist Token",
	"ShareX",
	"Kabberry Coin",
	"Bitcoin Adult",
	"Ether Kingdoms Token",
	"EOS TRUST",
	"GenesisX",
	"Origami",
	"RPICoin",
	"Ccore",
	"Decentralized Asset Trading Platform",
	"Beacon",
	"MedicCoin",
	"Bitcoin Classic",
	"GoPower",
	"CyberMusic",
	"FundRequest",
	"Elementrem",
	"Cyber Movie Chain",
	"bitJob",
	"PayCoin",
	"nDEX",
	"Gold Poker",
	"TokenDesk",
	"EnterCoin",
	"Castle",
	"ROIyal Coin",
	"Zealium",
	"Fivebalance",
	"Jupiter",
	"UOS Network",
	"InterCrone",
	"SF Capital",
	"Atheios",
	"Stipend",
	"BriaCoin",
	"Coin2.1",
	"bitSilver",
	"Spectrum",
	"Centurion",
	"Iungo",
	"EVOS",
	"Level Up Coin",
	"Dreamcoin",
	"BoostCoin",
	"Magic Cube Coin",
	"Havy",
	"MarteXcoin",
	"JavaScript Token",
	"MoneroV ",
	"Soverain",
	"EagleX",
	"Blakecoin",
	"Eva Cash",
	"4NEW",
	"Galactrum",
	"ALAX",
	"FuzzBalls",
	"Titcoin",
	"Phonecoin",
	"XOVBank",
	"PostCoin",
	"Ratecoin",
	"Fantasy Sports",
	"Bulleon",
	"CPUchain",
	"ParkByte",
	"NevaCoin",
	"GoldBlocks",
	"Datacoin",
	"Save Environment Token",
	"Global Crypto Alliance",
	"WITChain",
	"ARAW",
	"Absolute",
	"ConnectJob",
	"X-Coin",
	"ALL BEST ICO",
	"Natmin Pure Escrow",
	"High Voltage",
	"wys Token",
	"Kora Network Token",
	"BitGuild PLAT",
	"P2P Global Network",
	"KWHCoin",
	"Digital Money Bits",
	"Spectiv",
	"ArbitrageCT",
	"INDINODE",
	"Signatum",
	"Bionic",
	"Onix",
	"FidexToken",
	"SkyHub Coin",
	"iBTC",
	"Gexan",
	"FUTURAX",
	"Desire",
	"SparksPay",
	"CCUniverse",
	"Vivid Coin",
	"ICOBID",
	"Zayedcoin",
	"CryptoFlow",
	"Nyerium",
	"1X2 COIN",
	"Californium",
	"Stakinglab",
	"Japan Content Token",
	"Zurcoin",
	"ARbit",
	"Dalecoin",
	"CustomContractNetwork",
	"Bitcoin 21",
	"Rupaya",
	"Shivers",
	"onLEXpa",
	"Akroma",
	"SpreadCoin",
	"Bitcoinus",
	"Trexcoin",
	"PAXEX",
	"Luna Coin",
	"Couchain",
	"LuckySevenToken",
	"Mirai",
	"Open Trading Network",
	"MASTERNET",
	"VikkyToken",
	"SongCoin",
	"Litecred",
	"Crowdholding",
	"Alpha Coin",
	"Helper Search Token",
	"GINcoin",
	"Gratz",
	"e-Chat",
	"VectorAI",
	"Xenoverse",
	"Escroco Emerald",
	"Electrum Dark",
	"Cabbage",
	"DNotes",
	"Independent Money System",
	"Coinonat",
	"AmsterdamCoin",
	"Crystal Clear ",
	"Ragnarok",
	"Nekonium",
	"Quebecoin",
	"Carebit",
	"BitCoal",
	"Prime-XI",
	"Simmitri",
	"MustangCoin",
	"Comet",
	"Quantis Network",
	"MNPCoin",
	"BunnyToken",
	"Phantomx",
	"Dollar International",
	"Dollarcoin",
	"Peerguess",
	"CrevaCoin",
	"Bitvolt",
	"PLNcoin",
	"BitMoney",
	"BowsCoin",
	"MiloCoin",
	"WXCOINS",
	"LiteBitcoin",
	"PlatinumBAR",
	"Decentralized Crypto Token",
	"Cannation",
	"SpeedCash",
	"Experience Points",
	"Veltor",
	"Eurocoin",
	"HollyWoodCoin",
	"Flit Token",
	"Wild Beast Block",
	"MoX",
	"Crystal Token",
	"Nibble",
	"BenjiRolls",
	"PAWS Fund",
	"PosEx",
	"TravelNote",
	"SocialCoin",
	"iBank",
	"Fintab",
	"BROTHER",
	"Staker",
	"Storeum",
	"Dash Green",
	"Project-X",
	"Silverway",
	"ICOCalendar.Today",
	"SONO",
	"Secrets of Zurich",
	"Iconic",
	"LiteCoin Ultra",
	"X12 Coin",
	"LitecoinToken",
	"Xchange",
	"Concoin",
	"Dragon Option",
	"Qbic",
	"Benz",
	"Helpico",
	"Save and Gain",
	"Dinero",
	"Cointorox",
	"PonziCoin",
	"QYNO",
	"999",
	"Posscoin",
	"Argus",
	"Abulaba",
	"Zoomba",
	"Dystem",
	"UltraNote Coin",
	"LRM Coin",
	"Newton Coin Project",
	"HarmonyCoin",
	"Bitcoin Vault",
	"Union Fair Coin",
	"WaykiChain Governance Coin",
	"Polkadot",
	"NDN Link",
	"ECOChain",
	"Filecoin [Futures]",
	"Ontology Gas",
	"Gstcoin",
	"BKEX Token",
	"Tweebaa",
	"Bitsonic",
	"Soda Coin",
	"FairGame",
	"Decentralized Vulnerability Platform",
	"Sora",
	"AnimalGo",
	"DMM: Governance",
	"Balancer",
	"Two Prime FF1 Token",
	"Echoin",
	"3X Short Ethereum Token",
	"MeconCash",
	"3X Long Ethereum Token",
	"YottaChain",
	"ABCC Token",
	"Building Cities Beyond Blockchain",
	"VARC",
	"DEXTools",
	"Xenon",
	"Yobit Token",
	"TopChain",
	"Lux Bio Cell",
	"Binance KRW",
	"CryptoEnergy",
	"Orion Protocol",
	"Balloon-X",
	"Exchange Union",
	"Creditcoin",
	"Zynecoin",
	"RAKUN",
	"VinDax Coin",
	"INRToken",
	"Arweave",
	"Vinci",
	"Sensorium",
	"UMA",
	"Klaytn",
	"Barkis Network",
	"dForce",
	"Medium",
	"Ubique Chain Of Things",
	"Xank",
	"AAX Token",
	"Decentr",
	"4THPILLAR TECHNOLOGIES",
	"Oikos",
	"Coni",
	"FIO Protocol",
	"3X Long Bitcoin Token",
	"3X Long BNB Token",
	"Askobar Network",
	"Latamcash",
	"UBU",
	"LUCY",
	"Bispex",
	"STONK",
	"LinkToken",
	"Keystone of Opportunity & Knowledge",
	"ELYSIA",
	"3X Short Bitcoin Token",
	"BitCherry",
	"NOIZ",
	"Keep Network",
	"ShineChain",
	"PayProtocol",
	"Insight Protocol",
	"FinNexus",
	"Index Chain",
	"3x Long EOS Token",
	"Kadena",
	"QUEENBEE",
	"DARMA Cash",
	"3x Long XRP Token",
	"NXM",
	"Ystar",
	"Buxcoin",
	"Bananatok",
	"Whole Network",
	"BigBang Core",
	"Hdac",
	"ACE",
	"SOLBIT",
	"LinkArt",
	"Pamp Network",
	"KNOW",
	"Edgeware",
	"Rivex",
	"Treecle",
	"Defis",
	"Filenet",
	"Dash Cash",
	"Intelligent Investment Chain",
	"Dapp Token",
	"Imsmart",
	"Bitpayer Token",
	"NNB Token",
	"Brazilian Digital Token",
	"FinexboxToken",
	"3x Short EOS Token",
	"Freecash",
	"Bilaxy Token",
	"Crypto Holding Frank Token",
	"Gosama",
	"Tether Gold",
	"3X Long TRX Token",
	"ARCS",
	"QURAS",
	"3x Short XRP Token",
	"Super Bitcoin",
	"Ormeus Cash",
	"1x Short Bitcoin Token",
	"WiBX",
	"KingMoney",
	"Paris Saint-Germain Fan Token",
	"3x Short Litecoin Token",
	"Kingdom Game 4.0",
	"CNNS",
	"1x Long Bitcoin Implied Volatility Token",
	"HelixNetwork",
	"Bitscoin",
	"DigiFinexToken",
	"Aitheon",
	"MyToken",
	"Dfinity (IOU)",
	"AS Roma Fan Token",
	"Ti-Value",
	"3x Long Bitcoin SV Token",
	"OG Fan Token",
	"Unknown Fair Object",
	"Rarible",
	"ViteX Coin",
	"3x Long Bitcoin Cash Token",
	"DigiDinar",
	"Tesra",
	"Yuan Chain Coin",
	"Ormeus Ecosystem",
	"Axial Entertainment Digital Asset",
	"Buzzshow",
	"Spice",
	"3x Long Litecoin Token",
	"ProBit Token",
	"Sparkle",
	"FC Barcelona Fan Token",
	"RING X PLATFORM",
	"3x Long Tezos Token",
	"Engine",
	"Enzo",
	"EMOGI Network",
	"snglsDAO",
	"Aragon Court",
	"Helium",
	"V-Dimension",
	"DUO Network Token",
	"Paparazzi",
	"EYES Protocol",
	"VEHICLE DATA ARTIFICIAL INTELLIGENCE PLATFORM",
	"3X Short TRX Token",
	"3x Short Bitcoin SV Token",
	"Sylo",
	"Ycash",
	"YouLive Coin",
	"Electronero Pulse",
	"Galatasaray Fan Token",
	"ECOSC",
	"3x Short Bitcoin Cash Token",
	"LBK",
	"BuySell",
	"WETH",
	"HEIDI",
	"STATERA",
	"HOMT",
	"3X Short BNB Token",
	"United Bitcoin",
	"MarcoPolo Protocol",
	"XTRM COIN",
	"NextDAO",
	"DeFiChain",
	"DACC",
	"Botton",
	"Vectorium",
	"Affil Coin",
	"DMme",
	"PhoenixDAO",
	"SOMESING",
	"1X Short Ethereum Token",
	"KEY",
	"Money Token",
	"CoinMeet",
	"Atletico De Madrid Fan Token",
	"Bit Trust System",
	"CRYPTOFOREX",
	"Spockchain Network",
	"Zuflo Coin",
	"D Community",
	"Blockcloud",
	"Hintchain",
	"IZEROIUM",
	"MATH",
	"Lukki Operating Token",
	"Freight Trust & Clearing Network",
	"Promotion Coin",
	"Render Token",
	"REBIT",
	"Jack Token",
	"Marshal Lion Group Coin",
	"CryptoBharatCoin",
	"Curio",
	"CAPITAL X CELL",
	"BlockNoteX",
	"STPAY",
	"ETHPlus",
	"Saga",
	"Juventus Fan Token",
	"Hubi Token",
	"SimpleChain",
	"BitUP Token",
	"Pledge Coin",
	"CoinHe Token",
	"DigiDinar Token",
	"1Million Token",
	"Mogu",
	"Gomics",
	"HebeBlock",
	"ENTONE",
	"Blockchain Quotations Index Token",
	"Blue Baikal",
	"Dexter G",
	"EduCoin",
	"iOWN Token",
	"DSLA Protocol",
	"Robonomics.network",
	"Mochimo",
	"Release Project",
	"Red Box Dapp Token",
	"Cybereits",
	"EtherBone",
	"Jinbi Token",
	"KVANT",
	"DoDreamChain",
	"STK Coin",
	"IDK",
	"ThingsOperatingSystem",
	"Agoras Tokens",
	"CryptoBossCoin",
	"ChainZ Arena",
	"Codeo Token",
	"Treelion",
	"vSportCoin",
	"Davion",
	"Vectorspace AI",
	"UltrAlpha",
	"LOA Protocol",
	"CITEX Token",
	"DEXA COIN",
	"TeeCoin",
	"Rewardiqa",
	"AfroDex",
	"ODE",
	"EDC Blockchain",
	"IOEX",
	"FuturoCoin",
	"Tepleton",
	"BUMO",
	"Decurian",
	"Cipher Core Token",
	"BenePit Protocol",
	"ValueChain",
	"SPIN Protocol",
	"Kepler Network",
	"MERCI",
	"SafePost",
	"TranslateMe Network Token",
	"Ethereum eRush",
	"Sumcoin",
	"BitKAM",
	"Davies",
	"DragonVein",
	"BELIEVER",
	"CashBackPro",
	"xscoin",
	"StellarPayGlobal",
	"BITTO",
	"BITFXT COIN",
	"EcoDollar",
	"Globalvillage Ecosystem",
	"Bitgrin",
	"Diplexcoin",
	"TCOIN",
	"Bitcoin True",
	"LegalBlock",
	"MoCo Token",
	"BeeKan",
	"VerusCoin",
	"bitCEO",
	"Ixinium",
	"MEX",
	"Golden Token",
	"3x Short Tezos Token",
	"Bincentive",
	"Bitcloud Pro",
	"Twinkle",
	"Pawtocol",
	"QANplatform",
	"Opennity",
	"Skillchain",
	"Swapzilla",
	"Custody Token",
	"EzyStayz",
	"Joys Digital",
	"CRDT",
	"Wisdom Chain",
	"DXdao",
	"DarkPay",
	"GSENetwork",
	"renBTC",
	"VeraOne",
	"eosBLACK",
	"Emrals",
	"Sudan Gold Coin",
	"PalletOne",
	"Bitcoin File",
	"BeeEx",
	"Bitcoin BEP2",
	"DeepCloud AI",
	"Hive Dollar",
	"Infinity Economics",
	"NEOBITCOIN",
	"LEVELG",
	"Daikicoin",
	"Rivermount",
	"Aunite",
	"LivenPay",
	"Inverse Bitcoin Volatility Token",
	"FLAMA",
	"MyDexPay",
	"VN Token",
	"Global Game Coin",
	"Krypton Galaxy Coin",
	"CARAT",
	"Rowan Token",
	"Consentium",
	"PointPay",
	"SKINCHAIN",
	"Originate Coin",
	"Travel1Click",
	"WEBN token",
	"Sapphire",
	"Tchain",
	"VENJOCOIN",
	"Neuromorphic.io",
	"Asian-African Capital Chain",
	"Esports Token",
	"Ethereum Message Search",
	"Hyper Pay",
	"Mega Lottery Services Global",
	"AK12",
	"Beer Money",
	"Vanywhere",
	"CelCoin",
	"Bali Coin",
	"Kublaicoin",
	"Future1coin",
	"UniDollar",
	"En-Tan-Mo",
	"InnovaMinex",
	"ScPrime",
	"Flits",
	"LYFE",
	"Kratscoin",
	"Guapcoin",
	"BitcoinX",
	"Perth Mint Gold Token",
	"Blood",
	"WHEN Token",
	"OTCBTC Token",
	"DWS",
	"Mavro",
	"B91",
	"Receive Access Ecosystem",
	"Alchemy",
	"GoalTime N",
	"1irstGold",
	"Bitsten Token",
	"LemoChain",
	"Fanaticos Cash",
	"Pixie Coin",
	"Bitpanda Ecosystem Token",
	"Falcon Project",
	"ARMTOKEN",
	"BITCOINHEDGE",
	"Volt",
	"Simone",
	"SINERGIA",
	"SatoExchange Token",
	"BlockCDN",
	"TYCOON69",
	"Chainpay",
	"Emanate",
	"BLOCKIDCOIN",
	"LunchMoney",
	"pTokens BTC",
	"Tutor's Diary",
	"Becaz",
	"GM Holding",
	"MONNOS",
	"Simple Software Solutions",
	"Charg Coin",
	"TILWIKI",
	"RAKSUR",
	"Sparkster",
	"Crex Token",
	"The global index chain",
	"MACH Project",
	"Commerce Data Connection",
	"StarChain",
	"Gric Coin",
	"MORELO",
	"AZBI CORE",
	"Work Force Coin",
	"Game Stars",
	"The Hustle App",
	"Infinity Esaham",
	"BitcoinV",
	"Medalte",
	"Experience Token",
	"Historia",
	"Colletrix",
	"Social Lending Token",
	"Coin Controller Cash",
	"Mchain",
	"XDAG",
	"BuckHathCoin",
	"COMSA [XEM]",
	"Universal Protocol Token",
	"SkyMap",
	"Amun Ether 3x Daily Long",
	"UniPower",
	"Schilling-Coin",
	"MGC Token",
	"Bitcoffeen",
	"Newsolution",
	"SoPay",
	"USDA",
	"QUSD",
	"Odyssey",
	"Moozicore",
	"Lendroid Support Token",
	"Wallet Plus X",
	"Altbet",
	"Influence Chain",
	"Compound USDT",
	"Aeryus",
	"DFOhub",
	"First Bitcoin",
	"Endorsit",
	"Boogle",
	"TerraNova",
	"ZCore Token",
	"VOMER",
	"HeartBout Pay",
	"Cashhand",
	"Kryptofranc",
	"WowSecret",
	"Harcomia",
	"EncryptoTel [ETH]",
	"Defi",
	"ORS Group",
	"COMSA [ETH]",
	"Coinsto",
	"NSS Coin",
	"Tronipay",
	"Sombe",
	"Torex",
	"B ONE PAYMENT",
	"Wiki Token",
	"SuperEdge",
	"Smartup",
	"Hanacoin",
	"Demeter Chain",
	"Litecoin SV",
	"weBloc",
	"Litecash",
	"Quish Coin",
	"Voltz",
	"Instantily",
	"Five Star Coin",
	"Bitcurate",
	"Uranus",
	"CK USD",
	"CENTERCOIN",
	"Korbot",
	"Sierracoin",
	"THENODE",
	"Kahsh",
	"NOVA",
	"Jingtum Tech",
	"QPay",
	"Apple Network",
	"Aerotoken",
	"GermanCoin",
	"Boltt Coin ",
	"ClubCoin",
	"Bitcoin God",
	"EXOR",
	"PocketNode",
	"0cash",
	"PlusOneCoin",
	"Secure Cash",
	"ROMToken",
	"Small Love Potion",
	"Stellar Gold",
	"Wallabee",
	"One DEX",
	"7Eleven",
	"MobilinkToken",
	"Binance GBP Stable Coin",
	"ALA",
	"BOSCore",
	"Golden Ratio Token",
	"OceanChain",
	"Dragon Token",
	"Amun Ether 3x Daily Short",
	"Tratok",
	"SEER",
	"BTCMoon",
	"Junsonmingchncoin",
	"cUSD Currency",
	"Tradeplus",
	"EarnBet",
	"Valuto",
	"SpectreSecurityCoin",
	"Ladder Network Token",
	"Blockmason Link",
	"SovranoCoin",
	"ROS Coin",
	"Kemacoin",
	"Sexcoin",
	"WINCOIN",
	"PROUD Money",
	"Destiny Success",
	"SaveNode",
	"Centaure",
	"StockChain",
	"Usechain Token",
	"Global X Change Token",
	"QURA GLOBAL",
	"HondaisCoin",
	"Litbinex Coin",
	"RabbitCoin",
	"Quotient",
	"Bubble",
	"Axiom",
	"AvatarCoin",
	"Francs",
	"Aces",
	"BlazerCoin",
	"EmberCoin",
	"Wink",
	"Moving Cloud Coin",
	"MSD",
	"Ethereum Lite",
	"Qube",
	"Maggie",
	"Read",
	"Animation Vision Cash",
	"SalPay",
	"CHEX",
	"IOV BlockChain",
	"XTRD",
	"NewsToken",
	"CEDEX Coin",
	"Obitan Chain",
	"Hybrid Block",
	"KingXChain",
	"YUKI",
	"GazeCoin",
	"CMITCOIN",
	"CapdaxToken",
	"MediBit",
	"Bgogo Token",
	"TOKOK",
	"RoboCalls",
	"Big Bang Game Coin",
	"Xtock",
	"OOOBTC TOKEN",
	"HUDDL",
	"UTEMIS",
	"BIZKEY",
	"Atlas Token",
	"Muzika",
	"PATHHIVE ",
	"Lucky Block Network",
	"LevelApp Token",
	"Alphacon",
	"IOU",
	"Maya Preferred 223",
	"Volume Network",
	"BitcoinSoV",
	"Electronero",
	"VENA",
	"xCrypt Token",
	"LINK",
	"City Coin",
	"Oath Protocol",
	"Versess Coin",
	"MDtoken",
	"ALP Coin",
	"VERA",
	"Ethlyte Crypto",
	"Bitcoin & Company Network",
	"RigoBlock",
	"NairaX",
	"HGH Token",
	"Creatanium",
	"Global Reserve System",
	"1AI Token",
	"FLEX",
	"MEETtoken",
	"CitiOs",
	"Compound Dai",
	"Compound SAI",
	"Compound USD Coin",
	"Asac Coin",
	"SuperSkynet",
	"AdsByWiFi",
	"IBStoken",
	"SappChain",
	"MyTVchain",
	"PYRO Network (TRON)",
	"Pyrrhos Gold",
	"Hinto",
	"Entherfound",
	"Metaprediction",
	"The Transfer Token",
	"ASYAGRO",
	"United Bull Traders",
	"Cannadrix",
	"Egas",
	"Bluekey",
	"Compound Ether",
	"KYC.Crypto",
	"Amun Short Bitcoin Token",
	"IOOX System",
	"Amun Bitcoin 3x Daily Long",
	"Amun Bitcoin 3x Daily Short",
	"Compound Basic Attention Token",
	"Compound 0x",
	"Compound Wrapped BTC",
	"Compound Augur",
	"Nokencoin",
	"Bankroll Vault",
	"FLUX",
	"Props Token",
	"BLOCKCLOUT",
	"Crypto Cricket Club",
	"Content and AD Network",
	"NAM COIN",
	"RRCoin",
	"BiNGO.Fun",
	"Zerobank",
	"Blacknet",
	"Rally",
	"ESAX Token",
	"Kappi Network",
	"Lukiu",
	"Know Your Developer",
	"LOLTOKEN",
	"Unochain",
	"Wolfs Group",
	"London Football Exchange",
	"Zelerius",
	"Ethash Miner",
	"Scopuly Coin",
	"eToro Pound Sterling",
	"eToro New Zealand Dollar",
	"eToro Australian Dollar",
	"eToro Euro",
	"BTCDOWN",
	"DOCH COIN",
	"mStable USD",
	"bZx Vesting Token",
	"Unit Protocol"
  ]

export default names
