/**
 * data obtain from coinmarketcap api
 * end point is latest listing
 */
export const nameSymbolObj: { [name: string]: string } = {
	'999': '999',
	Bitcoin: 'BTC',
	Ethereum: 'ETH',
	Tether: 'USDT',
	XRP: 'XRP',
	'Bitcoin Cash': 'BCH',
	'Bitcoin SV': 'BSV',
	Cardano: 'ADA',
	Litecoin: 'LTC',
	'Binance Coin': 'BNB',
	'Crypto.com Coin': 'CRO',
	Chainlink: 'LINK',
	EOS: 'EOS',
	Tezos: 'XTZ',
	Stellar: 'XLM',
	TRON: 'TRX',
	Monero: 'XMR',
	'UNUS SED LEO': 'LEO',
	'USD Coin': 'USDC',
	VeChain: 'VET',
	'Huobi Token': 'HT',
	Neo: 'NEO',
	IOTA: 'MIOTA',
	'Ethereum Classic': 'ETC',
	Cosmos: 'ATOM',
	Dash: 'DASH',
	Zcash: 'ZEC',
	Maker: 'MKR',
	Ontology: 'ONT',
	NEM: 'XEM',
	Aave: 'LEND',
	Dogecoin: 'DOGE',
	HedgeTrade: 'HEDG',
	Compound: 'COMP',
	Ampleforth: 'AMPL',
	'Basic Attention Token': 'BAT',
	OKB: 'OKB',
	DigiByte: 'DGB',
	'Kyber Network': 'KNC',
	'Synthetix Network Token': 'SNX',
	Dai: 'DAI',
	'FTX Token': 'FTT',
	'0x': 'ZRX',
	Augur: 'REP',
	BitTorrent: 'BTT',
	Algorand: 'ALGO',
	'Paxos Standard': 'PAX',
	TrueUSD: 'TUSD',
	'OMG Network': 'OMG',
	Hyperion: 'HYN',
	Qtum: 'QTUM',
	ICON: 'ICX',
	Elrond: 'ERD',
	THETA: 'THETA',
	'Hedera Hashgraph': 'HBAR',
	Zilliqa: 'ZIL',
	Decred: 'DCR',
	'The Midas Touch Gold': 'TMTG',
	'Binance USD': 'BUSD',
	'Bitcoin Diamond': 'BCD',
	'Bitcoin Gold': 'BTG',
	Waves: 'WAVES',
	Lisk: 'LSK',
	'Enjin Coin': 'ENJ',
	Flexacoin: 'FXC',
	Terra: 'LUNA',
	Swipe: 'SXP',
	Ren: 'REN',
	'DxChain Token': 'DX',
	Loopring: 'LRC',
	Ravencoin: 'RVN',
	Nano: 'NANO',
	Siacoin: 'SC',
	Holo: 'HOT',
	HUSD: 'HUSD',
	MonaCoin: 'MONA',
	Nexo: 'NEXO',
	Divi: 'DIVI',
	Bytom: 'BTM',
	Verge: 'XVG',
	'Nervos Network': 'CKB',
	'ZB Token': 'ZB',
	'iExec RLC': 'RLC',
	Celsius: 'CEL',
	'ABBC Coin': 'ABBC',
	Quant: 'QNT',
	Bancor: 'BNT',
	Aurora: 'AOA',
	Blockstack: 'STX',
	IOST: 'IOST',
	Status: 'SNT',
	Horizen: 'ZEN',
	'Digitex Futures': 'DGTX',
	Kava: 'KAVA',
	'Band Protocol': 'BAND',
	Komodo: 'KMD',
	TomoChain: 'TOMO',
	Velas: 'VLX',
	'Matic Network': 'MATIC',
	Steem: 'STEEM',
	SwissBorg: 'CHSB',
	'Reserve Rights': 'RSR',
	BitShares: 'BTS',
	'KuCoin Shares': 'KCS',
	Decentraland: 'MANA',
	Hive: 'HIVE',
	WAX: 'WAXP',
	Aragon: 'ANT',
	MCO: 'MCO',
	Zcoin: 'XZC',
	aelf: 'ELF',
	Syscoin: 'SYS',
	Energi: 'NRG',
	Stratis: 'STRAT',
	'Ocean Protocol': 'OCEAN',
	Golem: 'GNT',
	Ardor: 'ARDR',
	HyperCash: 'HC',
	Unibright: 'UBT',
	Electroneum: 'ETN',
	'v.systems': 'VSYS',
	Chiliz: 'CHZ',
	Numeraire: 'NMR',
	'VeThor Token': 'VTHO',
	Ark: 'ARK',
	'RSK Infrastructure Framework': 'RIF',
	Aion: 'AION',
	Aeternity: 'AE',
	'Super Zero Protocol': 'SERO',
	Harmony: 'ONE',
	NULS: 'NULS',
	'PAX Gold': 'PAXG',
	'Pundi X': 'NPXS',
	MaidSafeCoin: 'MAID',
	Elastos: 'ELA',
	SOLVE: 'SOLVE',
	'Molecular Future': 'MOF',
	'Power Ledger': 'POWR',
	WaykiChain: 'WICC',
	Orbs: 'ORBS',
	pNetwork: 'PNT',
	IoTeX: 'IOTX',
	'Fetch.ai': 'FET',
	'Travala.com': 'AVA',
	CyberVein: 'CVT',
	Nimiq: 'NIM',
	IRISnet: 'IRIS',
	'Seele-N': 'SEELE',
	Wanchain: 'WAN',
	ReddCoin: 'RDD',
	Kusama: 'KSM',
	Utrust: 'UTK',
	Loki: 'LOKI',
	DAD: 'DAD',
	Storj: 'STORJ',
	'Gatechain Token': 'GT',
	Streamr: 'DATA',
	'STASIS EURO': 'EURS',
	'XinFin Network': 'XDCE',
	Ankr: 'ANKR',
	Gnosis: 'GNO',
	Waltonchain: 'WTC',
	Crypterium: 'CRPT',
	GXChain: 'GXC',
	FunFair: 'FUN',
	Request: 'REQ',
	'Theta Fuel': 'TFUEL',
	Cortex: 'CTXC',
	Fantom: 'FTM',
	'Ripio Credit Network': 'RCN',
	'Thunder Token': 'TT',
	'Huobi Pool Token': 'HPT',
	Beam: 'BEAM',
	MXC: 'MXC',
	'Voyager Token': 'VGX',
	Kleros: 'PNK',
	TrueChain: 'TRUE',
	'Origin Protocol': 'OGN',
	'Wirex Token': 'WXT',
	OriginTrail: 'TRAC',
	Dragonchain: 'DRGN',
	Fusion: 'FSN',
	'Haven Protocol': 'XHV',
	'BHEX Token': 'BHT',
	WINk: 'WIN',
	'Celer Network': 'CELR',
	PIVX: 'PIVX',
	Nebulas: 'NAS',
	'Project Pai': 'PAI',
	Insolar: 'XNS',
	'MX Token': 'MX',
	Metal: 'MTL',
	'12Ships': 'TSHP',
	Enigma: 'ENG',
	'Loom Network': 'LOOM',
	COTI: 'COTI',
	Chromia: 'CHR',
	'Tachyon Protocol': 'IPX',
	Mainframe: 'MFT',
	'Function X': 'FX',
	Grin: 'GRIN',
	HEX: 'HEX',
	'INO COIN': 'INO',
	'Counos X': 'CCXX',
	'Insight Chain': 'INB',
	BitcoinPoS: 'BPS',
	VestChain: 'VEST',
	'TNC Coin': 'TNC',
	Celo: 'CELO',
	Zelwin: 'ZLW',
	'Largo Coin': 'LRG',
	MINDOL: 'MIN',
	ThoreCoin: 'THR',
	MimbleWimbleCoin: 'MWC',
	Tap: 'XTP',
	'Wrapped Bitcoin': 'WBTC',
	BeautyPayCoin: 'BPC',
	botXcoin: 'BOTX',
	'Idea Chain Coin': 'ICH',
	'Metaverse Dualchain Network Architecture': 'DNA',
	THORChain: 'RUNE',
	'Advanced Internet Blocks': 'AIB',
	Homeros: 'HMR',
	'Baer Chain': 'BRC',
	'yearn.finance': 'YFI',
	Sologenic: 'SOLO',
	Cryptonex: 'CNX',
	Mixin: 'XIN',
	GlitzKoin: 'GTN',
	'Counos Coin': 'CCA',
	ERC20: 'ERC20',
	Centrality: 'CENNZ',
	QCash: 'QC',
	TerraKRW: 'KRT',
	'NewYork Exchange': 'NYE',
	Attila: 'ATT',
	Beldex: 'BDX',
	ThoreNext: 'THX',
	'bZx Protocol': 'BZRX',
	'Energy Web Token': 'EWT',
	'Bitball Treasure': 'BTRS',
	'STEM CELL COIN': 'SCC',
	Joule: 'JUL',
	PlayFuel: 'PLF',
	FABRK: 'FAB',
	'Poseidon Network': 'QQQ',
	'Bitbook Gambling': 'BXK',
	'BTU Protocol': 'BTU',
	Vitae: 'VITAE',
	Bytecoin: 'BCN',
	ShareToken: 'SHR',
	Breezecoin: 'BRZE',
	Bankera: 'BNK',
	Livepeer: 'LPT',
	'Karatgold Coin': 'KBC',
	'Orient Walt': 'HTDF',
	BitcoinHD: 'BHD',
	IDEX: 'IDEX',
	'BitMax Token': 'BTMX',
	'Buggyra Coin Zero': 'BCZERO',
	'Rocket Pool': 'RPL',
	Level01: 'LVX',
	Elamachain: 'ELAMA',
	Egoras: 'EGR',
	Nectar: 'NEC',
	'Handshake ': 'HNS',
	WhiteCoin: 'XWC',
	Tratin: 'TRAT',
	USDK: 'USDK',
	'UNI COIN': 'UNI',
	Stakenet: 'XSN',
	inSure: 'SURE',
	PLATINCOIN: 'PLC',
	Qubitica: 'QBIT',
	CasinoCoin: 'CSC',
	Chimpion: 'BNANA',
	'Bloomzed Token': 'BZT',
	AgaveCoin: 'AGVC',
	XeniosCoin: 'XNC',
	Massnet: 'MASS',
	Ultiledger: 'ULT',
	PRIZM: 'PZM',
	RChain: 'REV',
	'Davinci Coin': 'DAC',
	CRYPTO20: 'C20',
	sUSD: 'SUSD',
	'BigONE Token': 'ONE',
	Xensor: 'XSR',
	Polymath: 'POLY',
	DeviantCoin: 'DEV',
	'Hellenic Coin': 'HNC',
	NEXT: 'NET',
	Solana: 'SOL',
	Obyte: 'GBYTE',
	Civic: 'CVC',
	'NEST Protocol': 'NEST',
	APIX: 'APIX',
	'Folgory Coin': 'FLG',
	WazirX: 'WRX',
	'8X8 PROTOCOL': 'EXE',
	'Ecoreal Estate': 'ECOREAL',
	KardiaChain: 'KAI',
	BOSAGORA: 'BOA',
	Vid: 'VI',
	CRYPTOBUCKS: 'CBUCKS',
	'Neutrino Dollar': 'USDN',
	Everipedia: 'IQ',
	'Capricoin+': 'CPS',
	'WOM Protocol': 'WOM',
	Quantstamp: 'QSP',
	'V-ID': 'VIDT',
	Populous: 'PPT',
	StormX: 'STMX',
	Switcheo: 'SWTH',
	SingularityNET: 'AGI',
	Envion: 'EVN',
	Bluzelle: 'BLZ',
	ZEON: 'ZEON',
	QuarkChain: 'QKC',
	'NOIA Network': 'NOIA',
	TrustSwap: 'SWAP',
	Ignis: 'IGNIS',
	'1irstcoin': 'FST',
	'Dynamic Trading Rights': 'DTR',
	BitKan: 'KAN',
	'Atomic Wallet Coin': 'AWC',
	Gas: 'GAS',
	'AMO Coin': 'AMO',
	Cindicator: 'CND',
	GHOST: 'GHOST',
	ChainX: 'PCX',
	'Nash Exchange': 'NEX',
	Hxro: 'HXRO',
	Constellation: 'DAG',
	'LTO Network': 'LTO',
	Tierion: 'TNT',
	Dent: 'DENT',
	Tellor: 'TRB',
	Vertcoin: 'VTC',
	JUST: 'JST',
	'ARPA Chain': 'ARPA',
	'Uquid Coin': 'UQC',
	'ExtStock Token': 'XT',
	'Akropolis ': 'AKRO',
	CONTRACOIN: 'CTCN',
	Bonorum: 'BONO',
	Jewel: 'JWL',
	Perlin: 'PERL',
	SaluS: 'SLS',
	'Dusk Network': 'DUSK',
	CryptalDash: 'CRD',
	'Sport and Leisure': 'SNL',
	TROY: 'TROY',
	Melon: 'MLN',
	Lambda: 'LAMB',
	Groestlcoin: 'GRS',
	'Standard Tokenization Protocol': 'STPT',
	'Raiden Network Token': 'RDN',
	ILCoin: 'ILC',
	'Invictus Hyperion Fund': 'IHF',
	Elitium: 'EUM',
	Nexus: 'NXS',
	'Apollo Currency': 'APL',
	CONUN: 'CON',
	'Minter Network': 'BIP',
	MicroBitcoin: 'MBC',
	GoChain: 'GO',
	Contentos: 'COS',
	'WeShow Token': 'WET',
	QASH: 'QASH',
	Skycoin: 'SKY',
	BHPCoin: 'BHP',
	Newton: 'NEW',
	'Darico Ecosystem Coin': 'DEC',
	'Bit-Z Token': 'BZ',
	BORA: 'BORA',
	'Aleph.im': 'ALEPH',
	Clams: 'CLAM',
	'ZBG Token': 'ZT',
	'IoT Chain': 'ITC',
	'Aidos Kuneen': 'ADK',
	BIKI: 'BIKI',
	Wixlar: 'WIX',
	Factom: 'FCT',
	VideoCoin: 'VID',
	'Metaverse ETP': 'ETP',
	Bread: 'BRD',
	Kin: 'KIN',
	Monolith: 'TKN',
	TrustVerse: 'TRV',
	Dero: 'DERO',
	Cred: 'LBA',
	'LBRY Credits': 'LBC',
	'The Force Protocol': 'FOR',
	MediBloc: 'MED',
	Orchid: 'OXT',
	'Cryptoindex.com 100': 'CIX100',
	'Dragon Coins': 'DRG',
	Aergo: 'AERGO',
	'Gemini Dollar': 'GUSD',
	'Grid+': 'GRID',
	Unobtanium: 'UNO',
	MovieBloc: 'MBL',
	HYCON: 'HYC',
	CyberMiles: 'CMT',
	Carry: 'CRE',
	Proton: 'XPR',
	Nxt: 'NXT',
	PeepCoin: 'PCN',
	TOP: 'TOP',
	'Bitcoin 2': 'BTC2',
	NKN: 'NKN',
	'AEN Smart Token': 'AENS',
	TTC: 'TTC',
	'Cocos-BCX': 'COCOS',
	suterusu: 'SUTER',
	Einsteinium: 'EMC2',
	Rakon: 'RKN',
	Arcblock: 'ABT',
	'Game.com': 'GTC',
	'Titan Coin': 'TTN',
	FLETA: 'FLETA',
	'Spectre.ai Dividend Token': 'SXDT',
	Ultra: 'UOS',
	'Emirex Token': 'EMRX',
	'Dimension Chain': 'EON',
	Tael: 'WABI',
	REPO: 'REPO',
	Blocknet: 'BLOCK',
	Mithril: 'MITH',
	Electra: 'ECA',
	AirSwap: 'AST',
	Propy: 'PRO',
	'General Attention Currency': 'XAC',
	Metadium: 'META',
	'1SG': '1SG',
	ShipChain: 'SHIP',
	Anchor: 'ANCT',
	HyperDAO: 'HDAO',
	'#MetaHash': 'MHC',
	Telcoin: 'TEL',
	Nestree: 'EGG',
	Neblio: 'NEBL',
	FIBOS: 'FO',
	AdEx: 'ADX',
	DigixDAO: 'DGD',
	TenX: 'PAY',
	LATOKEN: 'LA',
	'Valor Token': 'VALOR',
	LiquidApps: 'DAPP',
	'EveryCoin ': 'EVY',
	Meta: 'MTA',
	BTSE: 'BTSE',
	Veritaseum: 'VERI',
	NavCoin: 'NAV',
	Cartesi: 'CTSI',
	VITE: 'VITE',
	'Time New Bank': 'TNB',
	Burst: 'BURST',
	Prometeus: 'PROM',
	MixMarvel: 'MIX',
	'Santiment Network Token': 'SAN',
	'BitForex Token': 'BF',
	'Moeda Loyalty Points': 'MDA',
	XMax: 'XMX',
	OST: 'OST',
	Wings: 'WINGS',
	'King DAG': 'KDAG',
	'Ethereum Meta': 'ETHM',
	'Morpheus.Network': 'MRPH',
	TaaS: 'TAAS',
	'CoinMetro Token': 'XCM',
	'Quantum Resistant Ledger': 'QRL',
	'Content Value Network': 'CVNT',
	DigitalBits: 'XDB',
	LCX: 'LCX',
	DREP: 'DREP',
	'Bibox Token': 'BIX',
	DMarket: 'DMT',
	FirmaChain: 'FCT',
	B2BX: 'B2B',
	'CWV Chain': 'CWV',
	BASIC: 'BASIC',
	VIDY: 'VIDY',
	'VNX Exchange': 'VNXLU',
	Gifto: 'GTO',
	'High Performance Blockchain': 'HPB',
	'Sentinel Protocol': 'UPP',
	XYO: 'XYO',
	DEAPcoin: 'DEP',
	Eminer: 'EM',
	Dock: 'DOCK',
	Zenon: 'ZNN',
	Castweet: 'CTT',
	Credits: 'CS',
	'EDC Blockchain [old]': 'EDC',
	Achain: 'ACT',
	DAOstack: 'GEN',
	PlayChip: 'PLA',
	'Effect.AI': 'EFX',
	PressOne: 'PRS',
	Origo: 'OGO',
	SynchroBitcoin: 'SNB',
	'Po.et': 'POE',
	LinkEye: 'LET',
	'Acute Angle Cloud': 'AAC',
	'CoinEx Token': 'CET',
	Sentivate: 'SNTVT',
	Pillar: 'PLR',
	Everex: 'EVX',
	'DOS Network': 'DOS',
	Polis: 'POLIS',
	IQeon: 'IQN',
	DDKoin: 'DDK',
	xDai: 'STAKE',
	ODEM: 'ODE',
	'Endor Protocol': 'EDR',
	'Digix Gold Token': 'DGX',
	GameCredits: 'GAME',
	Pluton: 'PLU',
	ChronoCoin: 'CRN',
	'QuickX Protocol': 'QCX',
	Cloudbric: 'CLB',
	'Moss Coin': 'MOC',
	ROOBEE: 'ROOBEE',
	Quark: 'QRK',
	'Ravencoin Classic': 'RVC',
	FirstBlood: '1ST',
	'Diamond Platform Token': 'DPT',
	'YOU COIN': 'YOU',
	SingularDTV: 'SNGLS',
	Blox: 'CDT',
	Peercoin: 'PPC',
	'Realio Network': 'RIO',
	LINA: 'LINA',
	SALT: 'SALT',
	'Genesis Vision': 'GVT',
	'FNB Protocol': 'FNB',
	WePower: 'WPR',
	Ruff: 'RUFF',
	'Dune Network': 'DUN',
	'Monero Classic': 'XMC',
	Bezant: 'BZNT',
	'QLC Chain': 'QLC',
	IONChain: 'IONC',
	Levolution: 'LEVL',
	'All Sports': 'SOC',
	BnkToTheFuture: 'BFT',
	IZE: 'IZE',
	Safe: 'SAFE',
	'Morpheus Labs': 'MITX',
	Particl: 'PART',
	district0x: 'DNT',
	Kcash: 'KCASH',
	'Steem Dollars': 'SBD',
	'Ferrum Network': 'FRM',
	OAX: 'OAX',
	HorusPay: 'HORUS',
	Metronome: 'MET',
	'DAPS Coin': 'DAPS',
	YOYOW: 'YOYOW',
	Nexty: 'NTY',
	'Atlas Protocol': 'ATP',
	Namecoin: 'NMC',
	'Safe Haven': 'SHA',
	XIO: 'XIO',
	Universa: 'UTNP',
	TAGZ5: 'TAGZ5',
	S4FE: 'S4F',
	Peculium: 'PCL',
	Robotina: 'ROX',
	MOAC: 'MOAC',
	Mooncoin: 'MOON',
	'United Traders Token': 'UTT',
	UGAS: 'UGAS',
	Egretia: 'EGT',
	EDUCare: 'EKT',
	'SIRIN LABS Token': 'SRN',
	Tokenomy: 'TEN',
	'0Chain': 'ZCN',
	USDQ: 'USDQ',
	Zano: 'ZANO',
	Wagerr: 'WGR',
	'Hydro Protocol': 'HOT',
	ProximaX: 'XPX',
	Neumark: 'NEU',
	OTOCASH: 'OTO',
	StakeCubeCoin: 'SCC',
	Asch: 'XAS',
	Covesting: 'COV',
	GreenPower: 'GRN',
	UnlimitedIP: 'UIP',
	'Pirate Chain': 'ARRR',
	FOAM: 'FOAM',
	'Insights Network': 'INSTAR',
	'U Network': 'UUU',
	Aeon: 'AEON',
	GHOSTPRISM: 'GHOST',
	Selfkey: 'KEY',
	'Lightning Bitcoin': 'LBTC',
	'Compound Coin': 'COMP',
	CryptoFranc: 'XCHF',
	'Clipper Coin': 'CCC',
	Lamden: 'TAU',
	AppCoins: 'APPC',
	POA: 'POA',
	SmartCash: 'SMART',
	SmartMesh: 'SMT',
	Viacoin: 'VIA',
	Budbo: 'BUBO',
	NPCoin: 'NPC',
	Revain: 'REV',
	Telos: 'TLOS',
	'INT Chain': 'INT',
	qiibee: 'QBX',
	HitChain: 'HIT',
	'Cosmo Coin': 'COSM',
	SonoCoin: 'SONO',
	'Digital Asset Guarantee Token': 'DAGT',
	'Measurable Data Token': 'MDT',
	'Jibrel Network': 'JNT',
	'BackPacker Coin': 'BPC',
	Howdoo: 'UDOO',
	VIBE: 'VIBE',
	'SoMee.Social': 'ONG',
	'T.OS': 'TOSC',
	'TE-FOOD': 'TFD',
	TokenClub: 'TCT',
	Ubiq: 'UBQ',
	Phore: 'PHR',
	Zel: 'ZEL',
	Leverj: 'LEV',
	'Bitcoin Rhodium': 'XRC',
	GAPS: 'GAP',
	GeoDB: 'GEO',
	ALQO: 'XLQ',
	BLOCKv: 'VEE',
	SwftCoin: 'SWFTC',
	'Darwinia Network': 'RING',
	smARTOFGIVING: 'AOG',
	Zap: 'ZAP',
	'Metrix Coin': 'MRX',
	'Global Cryptocurrency': 'GCC',
	'CEEK VR': 'CEEK',
	LockTrip: 'LOC',
	'Bitrue Coin': 'BTR',
	Ergo: 'ERG',
	Agrello: 'DLT',
	'OceanEx Token': 'OCE',
	Sense: 'SENSE',
	VNDC: 'VNDC',
	bitCNY: 'BITCNY',
	SunContract: 'SNC',
	Phantasma: 'SOUL',
	USDJ: 'USDJ',
	SymVerse: 'SYM',
	Monetha: 'MTH',
	Aladdin: 'ADN',
	GNY: 'GNY',
	Gulden: 'NLG',
	FLO: 'FLO',
	DigitalNote: 'XDN',
	XTRABYTES: 'XBY',
	MediShares: 'MDS',
	'Red Pulse Phoenix': 'PHX',
	BitTube: 'TUBE',
	SONM: 'SNM',
	Ternio: 'TERN',
	'Global Digital Content': 'GDC',
	KARMA: 'KARMA',
	Newscrypto: 'NWC',
	'GET Protocol': 'GET',
	Spiking: 'SPIKE',
	Agrocoin: 'AGRO',
	Viberate: 'VIB',
	'MIR COIN': 'MIR',
	Auctus: 'AUC',
	'Safex Token': 'SFT',
	Vexanium: 'VEX',
	Observer: 'OBSR',
	Flash: 'FLASH',
	VeriDocGlobal: 'VDG',
	MultiVAC: 'MTV',
	'Dawn Protocol': 'DAWN',
	Tokoin: 'TOKO',
	ZrCoin: 'ZRC',
	DATA: 'DTA',
	'Doc.com Token': 'MTC',
	BitCapitalVendor: 'BCV',
	NIX: 'NIX',
	BABB: 'BAX',
	Ondori: 'RSTR',
	Verasity: 'VRA',
	AmonD: 'AMON',
	Etheroll: 'DICE',
	Tripio: 'TRIO',
	Bitcore: 'BTX',
	CUTcoin: 'CUT',
	Precium: 'PCM',
	'Global Social Chain': 'GSC',
	Lykke: 'LKK',
	Cashaa: 'CAS',
	Dentacoin: 'DCN',
	'Hi Mutual Society': 'HMC',
	Plair: 'PLA',
	'Waves Enterprise': 'WEST',
	'DeepBrain Chain': 'DBC',
	'GoCrypto Token': 'GOC',
	HTMLCOIN: 'HTML',
	Sentinel: 'SENT',
	BitGreen: 'BITG',
	EURBASE: 'EBASE',
	'OneRoot Network': 'RNT',
	Everus: 'EVR',
	'Genaro Network': 'GNX',
	THEKEY: 'TKY',
	SIX: 'SIX',
	Incent: 'INCNT',
	PumaPay: 'PMA',
	Odyssey: 'ODY',
	Polybius: 'PLBT',
	QunQun: 'QUN',
	'JD Coin': 'JDC',
	'Blockmason Credit Protocol': 'BCPT',
	'Jarvis Network': 'JRT',
	BlackCoin: 'BLK',
	Mysterium: 'MYST',
	'BOX Token': 'BOX',
	Edge: 'DADI',
	Cryptocean: 'CRON',
	Kryll: 'KRL',
	Hydro: 'HYDRO',
	MVL: 'MVL',
	'Scorum Coins': 'SCR',
	ContentBox: 'BOX',
	'Nucleus Vision': 'NCASH',
	Credo: 'CREDO',
	'VNT Chain': 'VNT',
	Xaurum: 'XAUR',
	ZIMBOCASH: 'ZASH',
	PCHAIN: 'PI',
	Nyzo: 'NYZO',
	'Matrix AI Network': 'MAN',
	PolySwarm: 'NCT',
	'Color Platform': 'CLR',
	Counterparty: 'XCP',
	'Tidex Token': 'TDX',
	'Litecoin Cash': 'LCC',
	VeriBlock: 'VBK',
	Bloom: 'BLT',
	TrueFlip: 'TFL',
	Emercoin: 'EMC',
	CanonChain: 'CZR',
	'BitMart Token': 'BMX',
	'Rupiah Token': 'IDRT',
	PegNet: 'PEG',
	GridCoin: 'GRC',
	OneLedger: 'OLT',
	EOSDT: 'EOSDT',
	Hashgard: 'GARD',
	'Hiveterminal Token': 'HVN',
	Kambria: 'KAT',
	LINKA: 'LINKA',
	ColossusXT: 'COLX',
	'EOS Force': 'EOSC',
	VINchain: 'VIN',
	'Raven Protocol': 'RAVEN',
	Presearch: 'PRE',
	Constant: 'CONST',
	'Naka Bodhi Token': 'NBOT',
	'USDx stablecoin': 'USDX',
	YEE: 'YEE',
	DECOIN: 'DTEP',
	OKCash: 'OK',
	BOLT: 'BOLT',
	TERA: 'TERA',
	BaaSid: 'BAAS',
	Feathercoin: 'FTC',
	NAGA: 'NGC',
	NaPoleonX: 'NPX',
	CanYaCoin: 'CAN',
	'RSK Smart Bitcoin': 'RBTC',
	Futurepia: 'PIA',
	'Vipstar Coin': 'VIPS',
	'Pivot Token': 'PVT',
	PlatonCoin: 'PLTC',
	MintCoin: 'MINT',
	'Content Neutrality Network': 'CNN',
	Litex: 'LXT',
	CommerceBlock: 'CBT',
	Lympo: 'LYM',
	'Casino Betting Coin': 'CBC',
	Themis: 'GET',
	Cryptopay: 'CPAY',
	Peerplays: 'PPY',
	ECC: 'ECC',
	nOS: 'NOS',
	CoTrader: 'COT',
	Refereum: 'RFR',
	Esportbits: 'HLT',
	Blackmoon: 'BMC',
	Nasdacoin: 'NSD',
	Aryacoin: 'AYA',
	Spectrecoin: 'XSPEC',
	Lition: 'LIT',
	Spendcoin: 'SPND',
	Mobius: 'MOBI',
	CargoX: 'CXO',
	'Skrumble Network': 'SKM',
	pEOS: 'PEOS',
	Myriad: 'XMY',
	MenaPay: 'MPAY',
	'WPP TOKEN': 'WPP',
	'LNX Protocol': 'LNX',
	MESEFA: 'SEFA',
	carVertical: 'CV',
	Cardstack: 'CARD',
	Ixcoin: 'IXC',
	'Scry.info': 'DDD',
	ProChain: 'PRA',
	Airbloc: 'ABL',
	Cube: 'AUTO',
	Adshares: 'ADS',
	DAEX: 'DAX',
	'Winding Tree': 'LIF',
	'Callisto Network': 'CLO',
	SINOVATE: 'SIN',
	'apM Coin': 'APM',
	Nuggets: 'NUG',
	AMLT: 'AMLT',
	Trias: 'TRY',
	INLOCK: 'ILK',
	Maincoin: 'MNC',
	Rotharium: 'RTH',
	Apex: 'CPX',
	'IHT Real Estate Protocol': 'IHT',
	Ambrosus: 'AMB',
	BidiPass: 'BDP',
	WeOwn: 'CHX',
	'Abyss Token': 'ABYSS',
	'Credit Tag Chain': 'CTC',
	Swarm: 'SWM',
	Wowbit: 'WWB',
	Penta: 'PNT',
	Sharder: 'SS',
	HoryouToken: 'HYT',
	'Loopring [NEO]': 'LRN',
	'Blue Whale EXchange': 'BWX',
	'Spectre.ai Utility Token': 'SXUT',
	Rublix: 'RBLX',
	Zipper: 'ZIP',
	'Isiklar Coin': 'ISIKC',
	Cryptaur: 'CPT',
	'EXMO Coin': 'EXM',
	'Era Swap': 'ES',
	Flowchain: 'FLC',
	BIZZCOIN: 'BIZZ',
	Opacity: 'OPQ',
	Mcashchain: 'MCASH',
	Midas: 'MIDAS',
	Artfinity: 'AT',
	Radium: 'RADS',
	Enecuum: 'ENQ',
	'Pundi X NEM': 'NPXSXEM',
	Humanscape: 'HUM',
	SyncFab: 'MFG',
	Caspian: 'CSP',
	Beaxy: 'BXY',
	Stealth: 'XST',
	Pascal: 'PASC',
	BetProtocol: 'BEPRO',
	NuBits: 'USNBT',
	IntelliShare: 'INE',
	ChatCoin: 'CHAT',
	'Origin Sport': 'ORS',
	Tixl: 'MTXLT',
	Fatcoin: 'FAT',
	'Unikoin Gold': 'UKG',
	Cajutel: 'CAJ',
	Teloscoin: 'TELOS',
	Primas: 'PST',
	ZClassic: 'ZCL',
	Terracoin: 'TRC',
	PotCoin: 'POT',
	'Eterbase Coin': 'XBASE',
	PayBX: 'AXPR',
	'1World': '1WO',
	NativeCoin: 'N8V',
	Gleec: 'GLEEC',
	Unification: 'FUND',
	'PAC Global': 'PAC',
	Aeron: 'ARN',
	Crown: 'CRW',
	'Hubii Network': 'HBT',
	Sumokoin: 'SUMO',
	BOScoin: 'BOS',
	Change: 'CAG',
	TokenPay: 'TPAY',
	Bottos: 'BTO',
	'X8X Token': 'X8X',
	'Kuai Token': 'KT',
	bitUSD: 'BITUSD',
	Sparkpoint: 'SRK',
	eBitcoin: 'EBTC',
	'Blockchain Certified Data Token': 'BCDT',
	DEX: 'DEX',
	QChi: 'QCH',
	SnowGem: 'XSG',
	'Yap Stone': 'YAP',
	FansTime: 'FTI',
	Snetwork: 'SNET',
	HOMIHELP: 'HOMI',
	GoWithMi: 'GMAT',
	'UCA Coin': 'UCA',
	PIBBLE: 'PIB',
	'Restart Energy MWAT': 'MWAT',
	PUBLISH: 'NEWS',
	DAOBet: 'BET',
	'Fast Access Blockchain': 'FAB',
	Infinitecoin: 'IFC',
	'Sakura Bloom': 'SKB',
	Xaya: 'CHI',
	PLANET: 'PLA',
	'Bitcoin Atom': 'BCA',
	ZumCoin: 'ZUM',
	'CoinDeal Token': 'CDL',
	Krios: 'GIG',
	'X-CASH': 'XCASH',
	'I/O Coin': 'IOC',
	Vetri: 'VLD',
	Tolar: 'TOL',
	'Bean Cash': 'BITB',
	'Open Platform': 'OPEN',
	iEthereum: 'IETH',
	Banano: 'BAN',
	'Liquidity Network': 'LQD',
	LikeCoin: 'LIKE',
	'Colu Local Network': 'CLN',
	Pandacoin: 'PND',
	Amoveo: 'VEO',
	Databroker: 'DTX',
	REAL: 'REAL',
	ROAD: 'ROAD',
	'Chrono.tech': 'TIME',
	Minereum: 'MNE',
	'e-Gulden': 'EFL',
	Dether: 'DTH',
	Boolberry: 'BBR',
	'Trade Token X': 'TIOX',
	Sapien: 'SPN',
	BOOM: 'BOOM',
	indaHash: 'IDH',
	TRONCLASSIC: 'TRXC',
	NewYorkCoin: 'NYC',
	'Epic Cash': 'EPIC',
	EXRNchain: 'EXRN',
	Banca: 'BANCA',
	BlockStamp: 'BST',
	Remme: 'REM',
	Bidesk: 'BDK',
	Diamond: 'DMD',
	'ATC Coin': 'ATCC',
	Curecoin: 'CURE',
	Paypex: 'PAYX',
	'Education Ecosystem': 'LEDU',
	Denarius: 'D',
	SafeCoin: 'SAFE',
	'Netbox Coin': 'NBX',
	'Ink Protocol': 'XNK',
	SpaceChain: 'SPC',
	VeriCoin: 'VRC',
	'Coineal Token': 'NEAL',
	Smartlands: 'SLT',
	'Stronghold Token': 'SHX',
	Veil: 'VEIL',
	Substratum: 'SUB',
	CoinPoker: 'CHP',
	'Bitcoin Confidential': 'BC',
	Hashshare: 'HSS',
	SpankChain: 'SPANK',
	Rubycoin: 'RBY',
	NuShares: 'NSR',
	Flixxo: 'FLIXX',
	Dinastycoin: 'DCY',
	'42-coin': '42',
	TurtleCoin: 'TRTL',
	QuadrantProtocol: 'EQUAD',
	Tokenbox: 'TBX',
	Bismuth: 'BIS',
	Footballcoin: 'XFC',
	Axe: 'AXE',
	Azbit: 'AZ',
	Fountain: 'FTN',
	'AIDUS TOKEN': 'AIDUS',
	TEMCO: 'TEMCO',
	'AI Doctor': 'AIDOC',
	'Zenswap Network Token': 'ZNT',
	Blockport: 'BPT',
	Primecoin: 'XPM',
	Eden: 'EDN',
	MarketPeak: 'PEAK',
	Lunes: 'LUNES',
	Datum: 'DAT',
	ZPER: 'ZPR',
	Etherparty: 'FUEL',
	RealTract: 'RET',
	CryptoVerificationCoin: 'CVCC',
	ParkinGo: 'GOT',
	'FREE Coin': 'FREE',
	Cappasity: 'CAPP',
	'UNIVERSAL CASH': 'UCASH',
	Brickblock: 'BBK',
	EUNO: 'EUNO',
	'Beetle Coin': 'BEET',
	Lendingblock: 'LND',
	'MEET.ONE': 'MEETONE',
	'Gene Source Code Chain': 'GENE',
	Aventus: 'AVT',
	Merculet: 'MVP',
	'IG Gold': 'IGG',
	EncrypGen: 'DNA',
	Ubex: 'UBEX',
	eosDAC: 'EOSDAC',
	CPChain: 'CPC',
	Okschain: 'OKS',
	Rise: 'RISE',
	Pigeoncoin: 'PGN',
	PetroDollar: 'XPD',
	Swace: 'SWACE',
	Streamity: 'STM',
	WinCash: 'WCC',
	BOMB: 'BOMB',
	Omni: 'OMNI',
	Medicalchain: 'MTN',
	Datamine: 'DAM',
	DomRaider: 'DRT',
	Edgeless: 'EDG',
	MonetaryUnit: 'MUE',
	Rapids: 'RPD',
	NoLimitCoin: 'NLC2',
	Jobchain: 'JOB',
	'Bitex Global XBX Coin': 'XBX',
	ATLANT: 'ATL',
	adbank: 'ADB',
	BonusCloud: 'BXC',
	HyperExchange: 'HX',
	DeepOnion: 'ONION',
	BitNewChain: 'BTN',
	Ivy: 'IVY',
	Sessia: 'KICKS',
	Conceal: 'CCX',
	Zero: 'ZER',
	OracleChain: 'OCT',
	MalwareChain: 'MALW',
	Noku: 'NOKU',
	'DreamTeam Token': 'DREAM',
	Scala: 'XLA',
	'Block-Chain.com': 'BC',
	PayPie: 'PPP',
	Expanse: 'EXP',
	ToaCoin: 'TOA',
	Mindexcoin: 'MIC',
	Nework: 'NKC',
	Dynamic: 'DYN',
	FNKOS: 'FNKOS',
	CloakCoin: 'CLOAK',
	BQT: 'BQTX',
	Dovu: 'DOV',
	'ADAMANT Messenger': 'ADM',
	COVA: 'COVA',
	'0xBitcoin': '0xBTC',
	'2key.network': '2KEY',
	Matryx: 'MTX',
	LUKSO: 'LYXe',
	MargiX: 'MGX',
	'wave edu coin': 'WEC',
	Neurotoken: 'NTK',
	Lunyr: 'LUN',
	Cryptobuyer: 'XPT',
	Delphy: 'DPY',
	'MB8 Coin': 'MB8',
	Dimecoin: 'DIME',
	Wownero: 'WOW',
	'Traceability Chain': 'TAC',
	EchoLink: 'EKO',
	Humaniq: 'HMQ',
	Experty: 'EXY',
	'Digital Gold': 'GOLD',
	DecentBet: 'DBET',
	'Zebi Token': 'ZEBI',
	Auxilium: 'AUX',
	'HashBX ': 'HBX',
	ZelaaPayAE: 'ZPAE',
	STK: 'STK',
	'RedFOX Labs': 'RFOX',
	YGGDRASH: 'YEED',
	BitcoinZ: 'BTCZ',
	Pirl: 'PIRL',
	HalalChain: 'HLC',
	StableUSD: 'USDS',
	Xriba: 'XRA',
	MobileGo: 'MGO',
	Debitum: 'DEB',
	LHT: 'LHT',
	ZeuxCoin: 'ZUC',
	Ecobit: 'ECOB',
	GeoCoin: 'GEO',
	Switch: 'ESH',
	'FintruX Network': 'FTX',
	Nexxo: 'NEXXO',
	Bitswift: 'BITS',
	Amon: 'AMN',
	Membrana: 'MBN',
	'Asian Fintech': 'AFIN',
	Internxt: 'INXT',
	SHIELD: 'XSH',
	'NEXT.coin': 'NEXT',
	SmileyCoin: 'SMLY',
	KickToken: 'KICK',
	'PANTHEON X': 'XPN',
	Shift: 'SHIFT',
	Trollcoin: 'TROLL',
	Rate3: 'RTE',
	'Electronic Energy Coin': 'E2C',
	'Blocktrade Token': 'BTT',
	'ICNQ Token': 'ICNQ',
	Uptrennd: '1UP',
	'MARK.SPACE': 'MRK',
	'EXMR FDN': 'EXMR',
	POPCHAIN: 'PCH',
	'NeoWorld Cash': 'NASH',
	Qwertycoin: 'QWC',
	Bitsdaq: 'BQQQ',
	Moneytoken: 'IMT',
	Solaris: 'XLR',
	Upfiring: 'UFR',
	CannabisCoin: 'CANN',
	'NOW Token': 'NOW',
	'0xcert': 'ZXC',
	Pinkcoin: 'PINK',
	AtromG8: 'AG8',
	NeuroChain: 'NCC',
	ZENZO: 'ZNZ',
	Sphere: 'SPHR',
	USDX: 'USDX',
	'Snovian.Space': 'SNOV',
	'Ormeus Coin': 'ORMEUS',
	SolarCoin: 'SLR',
	Karbo: 'KRB',
	SafeInsure: 'SINS',
	Shivom: 'OMX',
	'Ether Zero': 'ETZ',
	'BitScreener Token': 'BITX',
	Fortuna: 'FOTA',
	Mercury: 'MER',
	GoldMint: 'MNTP',
	'Halo Platform': 'HALO',
	SBank: 'STS',
	Honest: 'HNST',
	'Nebula AI': 'NBAI',
	'Waves Community Token': 'WCT',
	NANJCOIN: 'NANJ',
	Stox: 'STX',
	GAMB: 'GMB',
	'Blockparty (BOXX Token)': 'BOXX',
	FYDcoin: 'FYD',
	'Bitcoin Plus': 'XBC',
	WeTrust: 'TRST',
	MineBee: 'MB',
	'Q DAO Governance token v1.0': 'QDAO',
	Espers: 'ESP',
	Phoenixcoin: 'PXC',
	HEAT: 'HEAT',
	'Business Credit Substitute': 'BCS',
	Mallcoin: 'MLC',
	MidasProtocol: 'MAS',
	FuzeX: 'FXT',
	'Trinity Network Credit': 'TNC',
	'Project WITH': 'WIKEN',
	Auroracoin: 'AUR',
	Ink: 'INK',
	Faceter: 'FACE',
	Devery: 'EVE',
	'Bitcoin Private': 'BTCP',
	'Pylon Network': 'PYLNT',
	Semux: 'SEM',
	'Coinsbit Token': 'CNB',
	Bitblocks: 'BBK',
	Rivetz: 'RVT',
	'Coinsuper Ecosystem Network': 'CEN',
	ESBC: 'ESBC',
	Alphacat: 'ACAT',
	Hush: 'HUSH',
	'VegaWallet Token': 'VGW',
	AICHAIN: 'AIT',
	Skychain: 'SKCH',
	Insureum: 'ISR',
	Lobstex: 'LOBS',
	SafeCapital: 'SCAP',
	Arbidex: 'ABX',
	ImageCoin: 'IMG',
	Olive: 'OLE',
	'MIB Coin': 'MIB',
	'TraDove B2BCoin': 'BBC',
	DATx: 'DATX',
	Patientory: 'PTOY',
	Merebel: 'MERI',
	"Bob's Repair": 'BOB',
	'Niobium Coin': 'NBC',
	DEEX: 'DEEX',
	'Crypto Sports': 'CSPN',
	Evedo: 'EVED',
	Playkey: 'PKT',
	'WinStars.live': 'WNL',
	AMATEN: 'AMA',
	'IQ.cash': 'IQ',
	Birake: 'BIR',
	LUXCoin: 'LUX',
	PIXEL: 'PXL',
	'Sentient Coin': 'SEN',
	StrongHands: 'SHND',
	TCASH: 'TCASH',
	CoinFi: 'COFI',
	Zippie: 'ZIPT',
	'Cashbery Coin': 'CBC',
	Novacoin: 'NVC',
	'Hacken Token': 'HAI',
	'Proton Token': 'PTT',
	ATMChain: 'ATM',
	'PlayCoin [ERC20]': 'PLX',
	CVCoin: 'CVN',
	'Zen Protocol': 'ZP',
	RED: 'RED',
	EverGreenCoin: 'EGC',
	WebDollar: 'WEBD',
	'Bitcoin Free Cash': 'BFC',
	BitCash: 'BITC',
	'TEAM (TokenStars)': 'TEAM',
	'CACHE Gold': 'CGT',
	ATN: 'ATN',
	BitCrystals: 'BCY',
	Orbitcoin: 'ORB',
	TouchCon: 'TOC',
	HiCoin: 'XHI',
	'Vodi X': 'VDX',
	'Electrify.Asia': 'ELEC',
	HEROcoin: 'PLAY',
	Graviocoin: 'GIO',
	DPRating: 'RATING',
	MyWish: 'WISH',
	TurtleNetwork: 'TN',
	Zeepin: 'ZPT',
	Sociall: 'SCL',
	ODUWA: 'OWC',
	DECENT: 'DCT',
	SPINDLE: 'SPD',
	'GlobalBoost-Y': 'BSTY',
	SIBCoin: 'SIB',
	Quiztok: 'QTCON',
	LocalCoinSwap: 'LCS',
	uPlexa: 'UPX',
	'Infinitus Token': 'INF',
	HOLD: 'HOLD',
	'Eureka Coin': 'ERK',
	HashCoin: 'HSC',
	'Sentinel Chain': 'SENC',
	GMB: 'GMB',
	BUZZCoin: 'BUZZ',
	Patron: 'PAT',
	EurocoinToken: 'ECTE',
	OLXA: 'OLXA',
	'Egoras Dollar': 'EUSD',
	Winco: 'WCO',
	'Jarvis+': 'JAR',
	Trittium: 'TRTT',
	Martkist: 'MARTK',
	'IDEX Membership': 'IDXM',
	AceD: 'ACED',
	'The ChampCoin': 'TCC',
	Smartshare: 'SSP',
	ZVCHAIN: 'ZVC',
	XEL: 'XEL',
	Eristica: 'ERT',
	BiblePay: 'BBP',
	'Safex Cash': 'SFX',
	'ICE ROCK MINING': 'ROCK2',
	FortKnoxster: 'FKX',
	FedoraCoin: 'TIPS',
	'AiLink Token': 'ALI',
	Playgroundz: 'IOG',
	Parachute: 'PAR',
	CryptoCarbon: 'CCRB',
	ION: 'ION',
	Starbase: 'STAR',
	FLIP: 'FLP',
	Vites: 'VITES',
	EBCoin: 'EBC',
	'Golos Blockchain': 'GLS',
	'Master Contract Token': 'MCT',
	VouchForMe: 'IPL',
	'MEXC Token': 'MEXC',
	'On.Live': 'ONL',
	Monarch: 'MT',
	Proxeus: 'XES',
	TigerCash: 'TCH',
	Manna: 'MANNA',
	DACSEE: 'DACS',
	Essentia: 'ESS',
	'Shadow Token': 'SHDW',
	Ulord: 'UT',
	View: 'VIEW',
	VeriSafe: 'VSF',
	PTON: 'PTON',
	Zeitcoin: 'ZEIT',
	BitBall: 'BTB',
	'Blue Protocol': 'BLUE',
	VeriumReserve: 'VRM',
	ExclusiveCoin: 'EXCL',
	HOQU: 'HQX',
	Raise: 'RAISE',
	Earneo: 'SNPC',
	adToken: 'ADT',
	'Ties.DB': 'TIE',
	Bittwatt: 'BWT',
	Qbao: 'QBT',
	'TV-TWO': 'TTV',
	AidCoin: 'AID',
	'Maverick Chain': 'MVC',
	BitDegree: 'BDG',
	Paytomat: 'PTI',
	'Lisk Machine Learning': 'LML',
	'Maximine Coin': 'MXM',
	Qredit: 'XQR',
	Rapidz: 'RPZX',
	imbrex: 'REX',
	CryCash: 'CRC',
	Maecenas: 'ART',
	SpectrumCash: 'XSM',
	'PHI Token': 'PHI',
	'Memetic / PepeCoin': 'MEME',
	'Alchemint Standards': 'SDS',
	'Internet of People': 'IOP',
	Megacoin: 'MEC',
	'Social Send': 'SEND',
	JET8: 'J8T',
	'Max Property Group': 'MPG',
	OWNDATA: 'OWN',
	Typerium: 'TYPE',
	HempCoin: 'THC',
	PAYCENT: 'PYN',
	'Ethereum Gold': 'ETG',
	Noir: 'NOR',
	'EncryptoTel [WAVES]': 'ETT',
	'Swarm City': 'SWT',
	Swap: 'XWP',
	SwiftCash: 'SWIFT',
	CoinUs: 'CNUS',
	HUNT: 'HUNT',
	XPA: 'XPA',
	Vether: 'VETH',
	Datawallet: 'DXT',
	Opus: 'OPT',
	TOKPIE: 'TKP',
	BetterBetting: 'BETR',
	GoNetwork: 'GOT',
	FujiCoin: 'FJC',
	CREDIT: 'CREDIT',
	Giant: 'GIC',
	Actinium: 'ACM',
	TrezarCoin: 'TZC',
	'Digital Insurance Token': 'DIT',
	Zilla: 'ZLA',
	Bancacy: 'BNY',
	Friendz: 'FDZ',
	'Bridge Protocol': 'BRDG',
	Motocoin: 'MOTO',
	'DAV Coin': 'DAV',
	TrueFeedBack: 'TFB',
	EnergiToken: 'ETK',
	'Baz Token': 'BAZT',
	PiplCoin: 'PIPL',
	Helix: 'HLIX',
	KuboCoin: 'KUBO',
	BeatzCoin: 'BTZC',
	'eXPerience Chain': 'XPC',
	OVCODE: 'OVC',
	'Block-Logic': 'BLTG',
	DopeCoin: 'DOPE',
	Zeusshield: 'ZSC',
	BioCoin: 'BIO',
	savedroid: 'SVD',
	Jetcoin: 'JET',
	'XcelToken Plus': 'XLAB',
	FlypMe: 'FYP',
	IXT: 'IXT',
	'Webflix Token': 'WFX',
	Bounty0x: 'BNTY',
	Masari: 'MSR',
	DABANKING: 'DAB',
	Neutron: 'NTRN',
	StarCoin: 'KST',
	Pakcoin: 'PAK',
	CryptoPing: 'PING',
	'Decentralized Machine Learning': 'DML',
	EventChain: 'EVC',
	Leadcoin: 'LDC',
	Aston: 'ATX',
	GoByte: 'GBX',
	DogeCash: 'DOGEC',
	'Ryo Currency': 'RYO',
	Coinlancer: 'CL',
	Privatix: 'PRIX',
	KekCoin: 'KEK',
	Celeum: 'CLX',
	Bitnation: 'XPAT',
	Cubiex: 'CBIX',
	LiteDoge: 'LDOGE',
	HelloGold: 'HGT',
	MyBit: 'MYB',
	DIMCOIN: 'DIM',
	Ignition: 'IC',
	'Ultimate Secure Cash': 'USC',
	Ouroboros: 'OURO',
	ZMINE: 'ZMN',
	DubaiCoin: 'DBIX',
	Graft: 'GRFT',
	Omnitude: 'ECOM',
	'Alpha Token': 'A',
	GoldFund: 'GFUN',
	BoutsPro: 'BOUTS',
	'x42 Protocol': 'X42',
	DeVault: 'DVT',
	'Primalbase Token': 'PBT',
	Equal: 'EQL',
	Nerva: 'XNV',
	AllSafe: 'ASAFE',
	'Crowd Machine': 'CMCT',
	eSDChain: 'SDA',
	Bitzeny: 'ZNY',
	AudioCoin: 'ADC',
	Utrum: 'OOT',
	BlitzPredict: 'XBP',
	CaixaPay: 'CXP',
	'IP Exchange': 'IPSX',
	'Indorse Token': 'IND',
	UpToken: 'UP',
	BZEdge: 'BZE',
	Scanetchain: 'SWC',
	MetaMorph: 'METM',
	Bethereum: 'BETHER',
	LanaCoin: 'LANA',
	'Ether-1': 'ETHO',
	Moneynet: 'MNC',
	'Monkey Project': 'MONK',
	eBoost: 'EBST',
	TrueDeck: 'TDP',
	WandX: 'WAND',
	'MorCrypto Coin': 'MOR',
	Adelphoi: 'ADL',
	InvestDigital: 'IDT',
	'Emerald Crypto': 'EMD',
	ArdCoin: 'ARDX',
	Blockpass: 'PASS',
	'FSBT API Token': 'FSBT',
	Dropil: 'DROP',
	'Helium Chain': 'HLM',
	Bitsum: 'BSM',
	Bigbom: 'BBO',
	Cobinhood: 'COB',
	PengolinCoin: 'PGO',
	Goldcoin: 'GLC',
	'ZUM TOKEN': 'ZUM',
	Startcoin: 'START',
	Bezop: 'BEZ',
	Ritocoin: 'RITO',
	Lethean: 'LTHN',
	'Signals Network': 'SGN',
	Ubricoin: 'UBN',
	Energycoin: 'ENRG',
	'Carboneum [C8] Token': 'C8',
	MMOCoin: 'MMO',
	'Profile Utility Token': 'PUT',
	NetKoin: 'NTK',
	'Amino Network': 'AMIO',
	Energo: 'TSL',
	Freicoin: 'FRC',
	Bolivarcoin: 'BOLI',
	'SignatureChain ': 'SIGN',
	Sharpay: 'S',
	RealChain: 'RCT',
	FarmaTrust: 'FTT',
	GravityCoin: 'GXX',
	'Alt.Estate token': 'ALT',
	EvenCoin: 'EVN',
	Maxcoin: 'MAX',
	'Silent Notary': 'SNTR',
	WOLLO: 'WLO',
	'Gems ': 'GEM',
	iDealCash: 'DEAL',
	Kuende: 'KUE',
	Peony: 'PNY',
	Matchpool: 'GUP',
	'PEPS Coin': 'PEPS',
	MesChain: 'MES',
	OptiToken: 'OPTI',
	Relex: 'RLX',
	InflationCoin: 'IFLT',
	Gravity: 'GZRO',
	'W Green Pay': 'WGP',
	Matrexcoin: 'MAC',
	'Thrive Token': 'THRT',
	Chronologic: 'DAY',
	SWYFT: 'SWYFTT',
	'The Currency Analytics': 'TCAT',
	Quasarcoin: 'QAC',
	Swing: 'SWING',
	ZCore: 'ZCR',
	'Bitcoin Incognito': 'XBI',
	Transcodium: 'TNS',
	Version: 'V',
	bitEUR: 'BITEUR',
	LIFE: 'LIFE',
	Gentarium: 'GTM',
	'Coin Lion': 'LION',
	'Bitcoin Token': 'BTCT',
	'OSA Token': 'OSA',
	'Bitcoin CZ': 'BCZ',
	LOCIcoin: 'LOCI',
	MktCoin: 'MLM',
	'Limitless VIP': 'VIP',
	WIZBL: 'WBL',
	'MTC Mesh Network': 'MTC',
	Truegame: 'TGAME',
	Kuverit: 'KUV',
	'Menlo One': 'ONE',
	HYPNOXYS: 'HYPX',
	EtherSportz: 'ESZ',
	Verify: 'CRED',
	BlueCoin: 'BLU',
	MFCoin: 'MFC',
	Universe: 'UNI',
	Yocoin: 'YOC',
	OBITS: 'OBITS',
	Arionum: 'ARO',
	'BoatPilot Token': 'NAVY',
	Pesetacoin: 'PTC',
	FirstCoin: 'FRST',
	Emphy: 'EPY',
	Storiqa: 'STQ',
	TENA: 'TENA',
	Rentberry: 'BERRY',
	Atonomi: 'ATMI',
	Synergy: 'SNRG',
	'Catex Token': 'CATT',
	Oxycoin: 'OXY',
	Birdchain: 'BIRD',
	Bonpay: 'BON',
	Zennies: 'ZENI',
	'Bitcoin Red': 'BTCRED',
	ebakus: 'EBK',
	'Artis Turba': 'ARTIS',
	'Hyper Speed Network': 'HSN',
	'Litecoin Plus': 'LCP',
	'PWR Coin': 'PWR',
	ONOToken: 'ONOT',
	AC3: 'AC3',
	BitSend: 'BSD',
	BitClave: 'CAT',
	BBSCoin: 'BBS',
	ZINC: 'ZINC',
	Eroscoin: 'ERO',
	'CryptoAds Marketplace': 'CRAD',
	BitBar: 'BTB',
	'Thore Cash': 'TCH',
	BEAT: 'BEAT',
	HeartBout: 'HB',
	'MAX Exchange Token': 'MAX',
	Veros: 'VRS',
	Webcoin: 'WEB',
	CROAT: 'CROAT',
	'PAL Network': 'PAL',
	'Business Credit Alliance Chain': 'BCAC',
	InsaneCoin: 'INSN',
	StarterCoin: 'STAC',
	SRCOIN: 'SRCOIN',
	CryptoBonusMiles: 'CBM',
	Bitstar: 'BITS',
	Bitcloud: 'BTDX',
	XDNA: 'XDNA',
	'Gossip Coin': 'GOSS',
	'StrongHands Masternode': 'SHMN',
	Carboncoin: 'CARBON',
	Unify: 'UNIFY',
	Veles: 'VLS',
	HeroNode: 'HER',
	Kalkulus: 'KLKS',
	Kobocoin: 'KOBO',
	Anoncoin: 'ANC',
	Grimm: 'GRIMM',
	MicroMoney: 'AMM',
	Elcoin: 'EL',
	'Vanta Network': 'VANTA',
	Elementeum: 'ELET',
	Bata: 'BTA',
	TrumpCoin: 'TRUMP',
	Naviaddress: 'NAVI',
	'Bitcoin Interest': 'BCI',
	PENG: 'PENG',
	'KZ Cash': 'KZC',
	Garlicoin: 'GRLC',
	'Innovative Bioresearch Classic': 'INNBCL',
	Rupee: 'RUP',
	Blur: 'BLUR',
	'HashNet BitEco': 'HNB',
	'Cashpayz Token': 'CPC',
	ParallelCoin: 'DUO',
	EtherGem: 'EGEM',
	InvestFeed: 'IFT',
	QUINADS: 'QUIN',
	SiaCashCoin: 'SCC',
	Bitradio: 'BRO',
	Suretly: 'SUR',
	'ACE (TokenStars)': 'ACE',
	Swapcoinz: 'SPAZ',
	'Fire Lotto': 'FLOT',
	'PoSW Coin': 'POSW',
	InterValue: 'INVE',
	Cryptonite: 'XCN',
	'Seal Network': 'SEAL',
	vSlice: 'VSL',
	Vidulum: 'VDL',
	Narrative: 'NRVE',
	Opal: 'OPAL',
	LEOcoin: 'LC4',
	Photon: 'PHO',
	CryptoSoul: 'SOUL',
	Bitfex: 'BFX',
	XGOX: 'XGOX',
	'Ifoods Chain': 'IFOOD',
	SophiaTX: 'SPHTX',
	Dynamite: 'DYNMT',
	'PLAAS FARMERS TOKEN': 'PLAAS',
	Paragon: 'PRG',
	'Plus-Coin': 'NPLC',
	'PYRO Network': 'PYRO',
	'MODEL-X-coin': 'MODX',
	'Fox Trading': 'FOXT',
	TajCoin: 'TAJ',
	PlayGame: 'PXG',
	'Deutsche eMark': 'DEM',
	'Bee Token': 'BEE',
	BlockCAT: 'CAT',
	AdHive: 'ADH',
	'NFX Coin': 'NFXC',
	bitBTC: 'BITBTC',
	Ethersocial: 'ESN',
	Aditus: 'ADI',
	Blockburn: 'BURN',
	CyberFM: 'CYFM',
	'Neutral Dollar ': 'NUSD',
	Paymon: 'PMNT',
	Zetacoin: 'ZET',
	'Ethereum Gold Project': 'ETGP',
	'Ethereum Cash': 'ECASH',
	Rimbit: 'RBT',
	Pyrk: 'PYRK',
	CrypticCoin: 'CRYP',
	ANON: 'ANON',
	Apollon: 'XAP',
	Fiii: 'FIII',
	TransferCoin: 'TX',
	Daneel: 'DAN',
	RoBET: 'ROBET',
	Hurify: 'HUR',
	'Taklimakan Network': 'TAN',
	Voise: 'VOISE',
	TOKYO: 'TOKC',
	KanadeCoin: 'KNDC',
	Netko: 'NETKO',
	'LALA World': 'LALA',
	Kurrent: 'KURT',
	TagCoin: 'TAG',
	'Global Currency Reserve': 'GCR',
	CYCLEAN: 'CCL',
	Digitalcoin: 'DGC',
	Bitether: 'BTR',
	CaluraCoin: 'CLC',
	GlobalToken: 'GLT',
	'Asian Dragon': 'AD',
	'Evil Coin': 'EVIL',
	'Guaranteed Ethurance Token Extra': 'GETX',
	INMAX: 'INX',
	Elysian: 'ELY',
	SkinCoin: 'SKIN',
	'2GIVE': '2GIVE',
	BitStation: 'BSTN',
	ProxyNode: 'PRX',
	'Social Activity Token': 'SAT',
	Civitas: 'CIV',
	SuperCoin: 'SUPER',
	Iridium: 'IRD',
	'Italian Lira': 'ITL',
	SounDAC: 'XSD',
	MultiCoinCasino: 'MCC',
	PRASM: 'PSM',
	RightMesh: 'RMESH',
	OPCoinX: 'OPCX',
	'Doge Token': 'DOGET',
	AquariusCoin: 'ARCO',
	VULCANO: 'VULC',
	Commercium: 'CMM',
	HyperQuant: 'HQT',
	Ultragate: 'ULG',
	'Mainstream For The Underground': 'MFTU',
	'Kind Ads Token': 'KIND',
	'Streamit Coin': 'STREAM',
	BitCoen: 'BEN',
	TrueVett: 'VME',
	PluraCoin: 'PLURA',
	Parkgene: 'GENE',
	SelfSell: 'SSC',
	'Innovative Bioresearch Coin': 'INNBC',
	Helex: 'HLX',
	BitRewards: 'BIT',
	DraftCoin: 'DFT',
	Bela: 'BELA',
	Regalcoin: 'REC',
	SONDER: 'SNR',
	PDATA: 'PDATA',
	'Bitcoin Zero': 'BZX',
	EtherInc: 'ETI',
	BitWhite: 'BTW',
	Impleum: 'IMPL',
	'BTC Lite': 'BTCL',
	'Stellar Classic': 'XLMX',
	'Niobio Cash': 'NBR',
	Bitgesell: 'BGL',
	BlockMesh: 'BMH',
	'No BS Crypto': 'NOBS',
	UChain: 'UCN',
	XMCT: 'XMCT',
	CommunityGeneration: 'CGEN',
	'Thar Token': 'THAR',
	'PUBLYTO Token': 'PUB',
	'Bitcoin Fast': 'BTCF',
	Autonio: 'NIO',
	DOWCOIN: 'DOW',
	KAASO: 'KAASO',
	Cheesecoin: 'CHEESE',
	Cryptojacks: 'CJ',
	CrowdWiz: 'WIZ',
	Knekted: 'KNT',
	'Joint Ventures': 'JOINT',
	Freyrchain: 'FREC',
	Micromines: 'MICRO',
	Thingschain: 'TIC',
	Arqma: 'ARQ',
	Xuez: 'XUEZ',
	Adzcoin: 'ADZ',
	'Universal Currency': 'UNIT',
	Arion: 'ARION',
	'Advanced Technology Coin': 'ARC',
	ChessCoin: 'CHESS',
	FantasyGold: 'FGC',
	WABnetwork: 'WAB',
	'Mobile Crypto Pay Coin': 'MCPC',
	Agrolot: 'AGLT',
	GoldenPyrex: 'GPYX',
	ATBCoin: 'ATB',
	TRAXIA: 'TM2',
	iTicoin: 'ITI',
	PopularCoin: 'POP',
	Moin: 'MOIN',
	SteepCoin: 'STEEP',
	Blocklancer: 'LNC',
	AirWire: 'WIRE',
	PureVidz: 'VIDZ',
	'CDX Network': 'CDX',
	'BLOC.MONEY': 'BLOC',
	Worldcore: 'WRC',
	Klimatas: 'KTS',
	BLAST: 'BLAST',
	ZeusNetwork: 'ZEUS',
	EthereumX: 'ETX',
	Ethouse: 'HORSE',
	PRiVCY: 'PRIV',
	Eternity: 'ENT',
	IGToken: 'IG',
	Exosis: 'EXO',
	'UNICORN Token': 'UNI',
	Biotron: 'BTRN',
	SnodeCoin: 'SND',
	Arepacoin: 'AREPA',
	'GCN Coin': 'GCN',
	Aigang: 'AIX',
	ClearPoll: 'POLL',
	Guider: 'GDR',
	IFX24: 'IFX24',
	VoteCoin: 'VOT',
	'APR Coin': 'APR',
	'Herbalist Token': 'HERB',
	'SCRIV NETWORK': 'SCRIV',
	'Theresa May Coin': 'MAY',
	EDRCoin: 'EDRC',
	'More Coin': 'MORE',
	InternationalCryptoX: 'INCX',
	'FUZE Token': 'FUZE',
	ETHplode: 'ETHPLO',
	'CYBR Token': 'CYBR',
	Linfinity: 'LFC',
	Italo: 'XTA',
	'Datarius Credit': 'DTRC',
	GuccioneCoin: 'GCC',
	bitGold: 'BITGOLD',
	Cream: 'CRM',
	Digiwage: 'WAGE',
	'Intelligent Trading Foundation': 'ITT',
	Rubies: 'RBIES',
	MojoCoin: 'MOJO',
	Blocktix: 'TIX',
	Payfair: 'PFR',
	'Coinchase Token': 'CCH',
	'Asura Coin': 'ASA',
	Aricoin: 'ARI',
	Ellaism: 'ELLA',
	DeltaChain: 'DELTA',
	EZOOW: 'EZW',
	Galilel: 'GALI',
	Bitcoiin: 'B2G',
	Authorship: 'ATS',
	Netrum: 'NTR',
	SmartCoin: 'SMC',
	Agora: 'VOTE',
	CFun: 'CFUN',
	Diligence: 'IRA',
	'Abitshadow Token': 'ABST',
	Cryptrust: 'CTRT',
	'Octoin Coin': 'OCC',
	MESG: 'MESG',
	BitStash: 'STASH',
	ShowHand: 'HAND',
	xEURO: 'XEUR',
	JSECOIN: 'JSE',
	BitcoiNote: 'BTCN',
	EveriToken: 'EVT',
	'Jade Currency': 'JADE',
	'Bitcoin Adult': 'BTAD',
	YoloCash: 'YLC',
	YENTEN: 'YTN',
	ELTCOIN: 'ELTCOIN',
	SHPING: 'SHPING',
	STRAKS: 'STAK',
	RefToken: 'REF',
	BERNcash: 'BERN',
	'Neural Protocol': 'NRP',
	BitRent: 'RNTB',
	'BitNautic Token': 'BTNT',
	EUNOMIA: 'ENTS',
	'Provoco Token': 'VOCO',
	Acoin: 'ACOIN',
	EnterCoin: 'ENTRC',
	GoHelpFund: 'HELP',
	Waletoken: 'WTN',
	GeyserCoin: 'GSR',
	'Tourist Token': 'TOTO',
	ShareX: 'SEXC',
	'Kabberry Coin': 'KKC',
	Origami: 'ORI',
	'EOS TRUST': 'EOST',
	GenesisX: 'XGS',
	'Connect Coin': 'XCON',
	RPICoin: 'RPI',
	'Decentralized Asset Trading Platform': 'DATP',
	'Ether Kingdoms Token': 'IMP',
	nDEX: 'NDX',
	'Bitcoin Classic': 'BXC',
	CyberMusic: 'CYMT',
	FundRequest: 'FND',
	Elementrem: 'ELE',
	'Cyber Movie Chain': 'CMCT',
	MedicCoin: 'MEDIC',
	bitJob: 'STU',
	PayCoin: 'XPY',
	'Gold Poker': 'GPKR',
	Castle: 'CSTL',
	TokenDesk: 'TDS',
	Fivebalance: 'FBN',
	InterCrone: 'ICR',
	Beacon: 'BECN',
	'UOS Network': 'UOS',
	'ROIyal Coin': 'ROCO',
	ImageCash: 'IMGC',
	'SF Capital': 'SFCP',
	Atheios: 'ATH',
	Spectrum: 'SPT',
	Stipend: 'SPD',
	BriaCoin: 'BRIA',
	'Coin2.1': 'C2',
	bitSilver: 'BITSILVER',
	Centurion: 'CNT',
	Iungo: 'ING',
	Citadel: 'CTL',
	EVOS: 'EVOS',
	'Level Up Coin': 'LUC',
	'Magic Cube Coin': 'MCC',
	BoostCoin: 'BOST',
	MarteXcoin: 'MXT',
	Zealium: 'NZL',
	Havy: 'HAVY',
	Dreamcoin: 'DRM',
	'MoneroV ': 'XMV',
	'JavaScript Token': 'JS',
	EagleX: 'EGX',
	'4NEW': 'KWATT',
	Blakecoin: 'BLC',
	Galactrum: 'ORE',
	XOVBank: 'XOV',
	'Eva Cash': 'EVC',
	ALAX: 'ALX',
	FuzzBalls: 'FUZZ',
	Titcoin: 'TIT',
	'ALL BEST ICO': 'ALLBI',
	Phonecoin: 'PHON',
	PostCoin: 'POST',
	Ratecoin: 'XRA',
	Bulleon: 'BUL',
	Soverain: 'SOVE',
	ParkByte: 'PKB',
	NevaCoin: 'NEVA',
	GoldBlocks: 'GB',
	'Save Environment Token': 'SET',
	'Global Crypto Alliance': 'CALL',
	WITChain: 'WIT',
	ARAW: 'ARAW',
	Absolute: 'ABS',
	Gexan: 'GEX',
	ConnectJob: 'CJT',
	'Natmin Pure Escrow': 'NAT',
	'X-Coin': 'XCO',
	'Kora Network Token': 'KNT',
	'High Voltage': 'HVCO',
	Jupiter: 'JUP',
	'P2P Global Network': 'P2PX',
	'wys Token': 'WYS',
	Spectiv: 'SIG',
	'BitGuild PLAT': 'PLAT',
	KWHCoin: 'KWH',
	Bionic: 'BNC',
	'Digital Money Bits': 'DMB',
	ArbitrageCT: 'ARCT',
	INDINODE: 'XIND',
	FidexToken: 'FEX',
	Signatum: 'SIGT',
	Onix: 'ONX',
	CPUchain: 'CPU',
	FUTURAX: 'FTXT',
	iBTC: 'IBTC',
	Desire: 'DSR',
	SparksPay: 'SPK',
	CCUniverse: 'UVU',
	Rupaya: 'RUPX',
	'Vivid Coin': 'VIVID',
	ICOBID: 'ICOB',
	Zayedcoin: 'ZYD',
	CryptoFlow: 'CFL',
	'1X2 COIN': '1X2',
	Californium: 'CF',
	'Japan Content Token': 'JCT',
	Zurcoin: 'ZUR',
	ARbit: 'ARB',
	Dalecoin: 'DALC',
	CustomContractNetwork: 'CCN',
	Stakinglab: 'LABX',
	'Bitcoin 21': 'XBTC21',
	'SkyHub Coin': 'SHB',
	Datacoin: 'DTC',
	Shivers: 'SHVR',
	onLEXpa: 'onLEXpa',
	Akroma: 'AKA',
	SpreadCoin: 'SPR',
	Trexcoin: 'TREX',
	MASTERNET: 'MASH',
	PAXEX: 'PAXEX',
	Couchain: 'COU',
	'Luna Coin': 'LUNA',
	Mirai: 'MRI',
	LuckySevenToken: 'LST',
	'Open Trading Network': 'OTN',
	VikkyToken: 'VIKKY',
	SongCoin: 'SONG',
	'Alpha Coin': 'APC',
	Nyerium: 'NYEX',
	Litecred: 'LTCR',
	Crowdholding: 'YUP',
	'Fantasy Sports': 'DFS',
	GoPower: 'GPT',
	Ccore: 'CCO',
	'Helper Search Token': 'HSN',
	GINcoin: 'GIN',
	Gratz: 'GRAT',
	'e-Chat': 'ECHT',
	VectorAI: 'VEC2',
	'Electrum Dark': 'ELD',
	Xenoverse: 'XENO',
	'Escroco Emerald': 'ESCE',
	Cabbage: 'CAB',
	DNotes: 'NOTE',
	'Independent Money System': 'IMS',
	Coinonat: 'CXT',
	AmsterdamCoin: 'AMS',
	'Crystal Clear ': 'CCT',
	Ragnarok: 'RAGNA',
	Nekonium: 'NUKO',
	Quebecoin: 'QBC',
	Carebit: 'CARE',
	BitCoal: 'COAL',
	'Prime-XI': 'PXI',
	'Dragon Option': 'DRAGON',
	MustangCoin: 'MST',
	'Dollar International': 'DOLLAR',
	Comet: 'CMT',
	'Quantis Network': 'QUAN',
	MNPCoin: 'MNP',
	BunnyToken: 'BUNNY',
	Phantomx: 'PNX',
	Dollarcoin: 'DLC',
	Bitcoinus: 'BITS',
	Peerguess: 'GUESS',
	CrevaCoin: 'CREVA',
	Bitvolt: 'VOLT',
	BitMoney: 'BIT',
	PLNcoin: 'PLNC',
	BowsCoin: 'BSC',
	PlatinumBAR: 'XPTX',
	MiloCoin: 'MILO',
	WXCOINS: 'WXC',
	LiteBitcoin: 'LBTC',
	Simmitri: 'SIM',
	'Decentralized Crypto Token': 'DCTO',
	Cannation: 'CNNC',
	SpeedCash: 'SCS',
	'Experience Points': 'XP',
	Veltor: 'VLT',
	Eurocoin: 'EUC',
	HollyWoodCoin: 'HWC',
	'Flit Token': 'FLT',
	'Wild Beast Block': 'WBB',
	MoX: 'MOX',
	Nibble: 'NBXC',
	BenjiRolls: 'BENJI',
	'PAWS Fund': 'PAWS',
	PosEx: 'PEX',
	TravelNote: 'TVNT',
	SocialCoin: 'SOCC',
	'Crystal Token': 'CYL',
	iBank: 'IBANK',
	'Dash Green': 'DASHG',
	Fintab: 'FNTB',
	BROTHER: 'BRAT',
	Staker: 'STR',
	Storeum: 'STO',
	Silverway: 'SLV',
	'Project-X': 'NANOX',
	'ICOCalendar.Today': 'ICT',
	SONO: 'SONO',
	'Secrets of Zurich': 'SOZ',
	Iconic: 'ICON',
	'LiteCoin Ultra': 'LTCU',
	'X12 Coin': 'X12',
	LitecoinToken: 'LTK',
	Xchange: 'XCG',
	Concoin: 'CONX',
	Qbic: 'QBIC',
	Benz: 'BENZ',
	Helpico: 'HELP',
	'Save and Gain': 'SANDG',
	Dinero: 'DIN',
	Cointorox: 'OROX',
	PonziCoin: 'PONZI',
	QYNO: 'QNO',
	Posscoin: 'POSS',
	Argus: 'ARGUS',
	Abulaba: 'AAA',
	Zoomba: 'ZBA',
	Dystem: 'DTEM',
	'UltraNote Coin': 'XUN',
	'LRM Coin': 'LRM',
	'Newton Coin Project': 'NCP',
	HarmonyCoin: 'HMC',
	'Bitcoin Vault': 'BTCV',
	'Union Fair Coin': 'UFC',
	Polkadot: 'DOT',
	'WaykiChain Governance Coin': 'WGRT',
	'NDN Link': 'NDN',
	ECOChain: 'ECOC',
	'Filecoin [Futures]': 'FIL',
	'Ontology Gas': 'ONG',
	Gstcoin: 'GST',
	'BKEX Token': 'BKK',
	Tweebaa: 'TWEE',
	Bitsonic: 'BSC',
	'Soda Coin': 'SOC',
	FairGame: 'FAIR',
	AnimalGo: 'GOM2',
	'DMM: Governance': 'DMG',
	Balancer: 'BAL',
	'Two Prime FF1 Token': 'FF1',
	Sora: 'XOR',
	Xenon: 'XEN',
	'3X Short Ethereum Token': 'ETHBEAR',
	'ABCC Token': 'AT',
	'3X Long Ethereum Token': 'ETHBULL',
	YottaChain: 'YTA',
	'Building Cities Beyond Blockchain': 'BCB',
	Echoin: 'EC',
	'Decentralized Vulnerability Platform': 'DVP',
	'Lux Bio Cell': 'LBXC',
	CryptoEnergy: 'CNRG',
	VARC: 'VARC',
	'Yobit Token': 'YO',
	'AAX Token': 'AAB',
	DEXTools: 'DEXT',
	RAKUN: 'RAKU',
	TopChain: 'TOPC',
	'Binance KRW': 'BKRW',
	Creditcoin: 'CTC',
	'Balloon-X': 'BLX',
	'Exchange Union': 'XUC',
	UMA: 'UMA',
	Arweave: 'AR',
	INRToken: 'INRT',
	'Orion Protocol': 'ORN',
	'VinDax Coin': 'VD',
	Vinci: 'VINCI',
	Sensorium: 'SENSO',
	Zynecoin: 'ZYN',
	dForce: 'DF',
	'Barkis Network': 'BKS',
	BitCherry: 'BCHC',
	'4THPILLAR TECHNOLOGIES': 'FOUR',
	MeconCash: 'MCH',
	Klaytn: 'KLAY',
	Medium: 'MDM',
	Oikos: 'OKS',
	Xank: 'XANK',
	'3X Long Bitcoin Token': 'BULL',
	Coni: 'CONI',
	'FIO Protocol': 'FIO',
	'DARMA Cash': 'DMCH',
	'Keystone of Opportunity & Knowledge': 'KOK',
	Decentr: 'DEC',
	Bispex: 'BPX',
	'Askobar Network': 'ASKO',
	'3X Long BNB Token': 'BNBBULL',
	UBU: 'UBU',
	NOIZ: 'NOIZ',
	STONK: 'STONK',
	LinkToken: 'LTK',
	LUCY: 'LUCY',
	'3x Long EOS Token': 'EOSBULL',
	Defis: 'XGM',
	ELYSIA: 'EL',
	ShineChain: 'SHE',
	PayProtocol: 'PCI',
	'Index Chain': 'IDX',
	FinNexus: 'FNX',
	Kadena: 'KDA',
	'Keep Network': 'KEEP',
	'3X Short Bitcoin Token': 'BEAR',
	'Insight Protocol': 'INX',
	'3x Long Litecoin Token': 'LTCBULL',
	'Ubique Chain Of Things': 'UCT',
	Latamcash: 'LMCH',
	QUEENBEE: 'QBZ',
	Ystar: 'YSR',
	SOLBIT: 'SBT',
	Imsmart: 'IMT',
	NXM: 'NXM',
	Bananatok: 'BNA',
	'3x Long XRP Token': 'XRPBULL',
	Treecle: 'TRCL',
	'Pamp Network': 'PAMP',
	LinkArt: 'LAR',
	KNOW: 'KNOW',
	ACE: 'ACE',
	Rivex: 'RVX',
	'Whole Network': 'NODE',
	Hdac: 'HDAC',
	Buxcoin: 'BUX',
	Edgeware: 'EDG',
	'Dapp Token': 'DAPPT',
	'Dash Cash': 'DSC',
	Filenet: 'FN',
	'Intelligent Investment Chain': 'IIC',
	'Bitpayer Token': 'BPT',
	'NNB Token': 'NNB',
	'BigBang Core': 'BBC',
	'Paris Saint-Germain Fan Token': 'PSG',
	'3x Short Litecoin Token': 'LTCBEAR',
	'Bilaxy Token': 'BIA',
	'3X Long TRX Token': 'TRXBULL',
	FinexboxToken: 'FNB',
	QURAS: 'XQC',
	Freecash: 'FCH',
	WiBX: 'WBX',
	'Tether Gold': 'XAUT',
	ARCS: 'ARX',
	'3x Short EOS Token': 'EOSBEAR',
	Gosama: 'GOS',
	'AS Roma Fan Token': 'ASR',
	'Crypto Holding Frank Token': 'CHFT',
	KingMoney: 'KIM',
	'1x Short Bitcoin Token': 'HEDGE',
	'OG Fan Token': 'OG',
	'Ormeus Cash': 'OMC',
	DigiFinexToken: 'DFT',
	HelixNetwork: 'MHLX',
	'YouLive Coin': 'UC',
	'Kingdom Game 4.0': 'KDG',
	'1x Long Bitcoin Implied Volatility Token': 'BVOL',
	CNNS: 'CNNS',
	'3x Short XRP Token': 'XRPBEAR',
	Bitscoin: 'BTCX',
	MyToken: 'MT',
	'FC Barcelona Fan Token': 'BAR',
	Aitheon: 'ACU',
	'Brazilian Digital Token': 'BRZ',
	'3x Long Bitcoin Cash Token': 'BCHBULL',
	'Dfinity (IOU)': 'DFN',
	'Ormeus Ecosystem': 'ECO',
	'Super Bitcoin': 'SBTC',
	'ViteX Coin': 'VX',
	'Ti-Value': 'TV',
	Ycash: 'YEC',
	Rarible: 'RARI',
	'3x Long Bitcoin SV Token': 'BSVBULL',
	'Unknown Fair Object': 'UFO',
	'Yuan Chain Coin': 'YCC',
	Buzzshow: 'GLDY',
	DigiDinar: 'DDR',
	Spice: 'SPICE',
	Tesra: 'TSR',
	'Galatasaray Fan Token': 'GAL',
	'ProBit Token': 'PROB',
	Sparkle: 'SPRKL',
	Engine: 'EGCC',
	ECOSC: 'ECU',
	Enzo: 'NZO',
	'Axial Entertainment Digital Asset': 'AXL',
	Helium: 'HNT',
	snglsDAO: 'SGT',
	DMme: 'DMME',
	'V-Dimension': 'VOLLAR',
	'Aragon Court': 'ANJ',
	Paparazzi: 'PAZZI',
	LBK: 'LBK',
	'VEHICLE DATA ARTIFICIAL INTELLIGENCE PLATFORM': 'VAIP',
	'Atletico De Madrid Fan Token': 'ATM',
	'Electronero Pulse': 'ETNXP',
	'3x Long Tezos Token': 'XTZBULL',
	'DUO Network Token': 'DUO',
	'3X Short TRX Token': 'TRXBEAR',
	'3x Short Bitcoin Cash Token': 'BCHBEAR',
	Sylo: 'SYLO',
	'3X Short BNB Token': 'BNBBEAR',
	DACC: 'DACC',
	'RING X PLATFORM': 'RINGX',
	'EYES Protocol': 'EYES',
	STATERA: 'STA',
	HEIDI: 'HDI',
	'United Bitcoin': 'UBTC',
	'3x Short Bitcoin SV Token': 'BSVBEAR',
	'Spockchain Network': 'SPOK',
	Blockcloud: 'BLOC',
	'EMOGI Network': 'LOL',
	'CAPITAL X CELL': 'CXC',
	PhoenixDAO: 'PHNX',
	SOMESING: 'SSX',
	DeFiChain: 'DFI',
	NextDAO: 'NAX',
	Vectorium: 'VCTP',
	WETH: 'WETH',
	'Affil Coin': 'AC',
	Botton: 'BOC',
	'Juventus Fan Token': 'JUV',
	'XTRM COIN': 'XTRM',
	HOMT: 'HOMT',
	'MarcoPolo Protocol': 'MAP',
	'1X Short Ethereum Token': 'ETHHEDGE',
	'Money Token': 'MNT',
	'D Community': 'DILI',
	CoinMeet: 'MEET',
	'Zuflo Coin': 'ZFL',
	'Freight Trust & Clearing Network': 'EDI',
	IZEROIUM: 'IZER',
	CRYPTOFOREX: 'CFX',
	Mochimo: 'MCM',
	MATH: 'MATH',
	'Lukki Operating Token': 'LOT',
	'Promotion Coin': 'PC',
	REBIT: 'KEYT',
	Curio: 'CUR',
	Hintchain: 'HINT',
	'Jack Token': 'JACK',
	'Render Token': 'RNDR',
	HebeBlock: 'HEBE',
	'Marshal Lion Group Coin': 'MLGC',
	CryptoBharatCoin: 'CBC',
	BlockNoteX: 'BNOX',
	STPAY: 'STP',
	SimpleChain: 'SIMPLE',
	KVANT: 'KVNT',
	Davion: 'DAVP',
	'Hubi Token': 'HUB',
	ETHPlus: 'ETHP',
	Mogu: 'MOGX',
	'BitUP Token': 'BUT',
	Saga: 'SGA',
	'CoinHe Token': 'CHT',
	'Blockchain Quotations Index Token': 'BQT',
	'CITEX Token': 'CTT',
	KEY: 'KEY',
	'Dexter G': 'DXG',
	'1Million Token': '1MT',
	Gomics: 'GOM',
	'Pledge Coin': 'PLG',
	'Blue Baikal': 'BBC',
	UltrAlpha: 'UAT',
	'ChainZ Arena': 'SOUL',
	Kublaicoin: 'KUB',
	EtherBone: 'ETHBN',
	'Release Project': 'REL',
	'Robonomics.network': 'XRT',
	Cybereits: 'CRE',
	IDK: 'IDK',
	'iOWN Token': 'iOWN',
	'Red Box Dapp Token': 'RBD',
	ENTONE: 'ENTONE',
	BuySell: 'BULL',
	DoDreamChain: 'DRM',
	'STK Coin': 'STK',
	'Cipher Core Token': 'CIPHC',
	'Codeo Token': 'CODEO',
	'Agoras Tokens': 'AGRS',
	'Jinbi Token': 'JNB',
	'LOA Protocol': 'LOA',
	'DSLA Protocol': 'DSLA',
	'DEXA COIN': 'DEXA',
	Treelion: 'TRN',
	CryptoBossCoin: 'CBC',
	'EDC Blockchain': 'EDC',
	BUMO: 'BU',
	'Neuromorphic.io': 'NMP',
	TeeCoin: 'TEC',
	Rewardiqa: 'REW',
	ODE: 'ODE',
	AfroDex: 'AfroX',
	'BenePit Protocol': 'BNP',
	Tepleton: 'TEP',
	IOEX: 'IOEX',
	ThingsOperatingSystem: 'TOS',
	DragonVein: 'DVC',
	Decurian: 'ECU',
	Bitgrin: 'XBG',
	xscoin: 'XSC',
	'Vectorspace AI': 'VXV',
	Blood: 'BLOOD',
	'DigiDinar Token': 'DDRT',
	FuturoCoin: 'FTO',
	Sumcoin: 'SUM',
	'Kepler Network': 'KMW',
	bitCEO: 'BCEO',
	MERCI: 'MERCI',
	EcoDollar: 'ECOS',
	'Ethereum eRush': 'EER',
	Davies: 'DVS',
	BITTO: 'BITTO',
	EduCoin: 'EDU',
	BitKAM: 'KAM',
	'Bitcoin BEP2': 'BTCB',
	'MoCo Token': 'MoCo',
	BELIEVER: 'BLVR',
	BeeKan: 'BKBT',
	SafePost: 'STAMP',
	'Wisdom Chain': 'WDC',
	Diplexcoin: 'DLX',
	'BITFXT COIN': 'BXT',
	Emrals: 'EMRALS',
	GSENetwork: 'GSE',
	'Custody Token': 'CUST',
	CashBackPro: 'CBP',
	'Bitcoin True': 'BTCT',
	LegalBlock: 'LBK',
	SKINCHAIN: 'SKC',
	VerusCoin: 'VRSC',
	Pawtocol: 'UPI',
	'3x Short Tezos Token': 'XTZBEAR',
	MEX: 'MEX',
	'Bitcloud Pro': 'BPRO',
	'Bit Trust System': 'BIUT',
	Twinkle: 'TKT',
	Bincentive: 'BCNT',
	'Golden Token': 'GOLD',
	Opennity: 'OPNN',
	QANplatform: 'QARK',
	'Joys Digital': 'JOYS',
	'Inverse Bitcoin Volatility Token': 'IBVOL',
	'Global Game Coin': 'GGC',
	EzyStayz: 'EZY',
	Swapzilla: 'SWZL',
	VeraOne: 'VRO',
	DarkPay: 'D4RK',
	Skillchain: 'SKI',
	CRDT: 'CRDT',
	'Hive Dollar': 'HBD',
	eosBLACK: 'BLACK',
	Vanywhere: 'VANY',
	'Bitcoin File': 'BIFI',
	PalletOne: 'PTN',
	'Sudan Gold Coin': 'SGC',
	DXdao: 'DXD',
	renBTC: 'RENBTC',
	'DeepCloud AI': 'DEEP',
	'Infinity Economics': 'XIN',
	BeeEx: 'BEE',
	Simone: 'SON',
	LEVELG: 'LEVELG',
	Ixinium: 'XXA',
	'TranslateMe Network Token': 'TMN',
	FLAMA: 'FMA',
	ScPrime: 'SCP',
	'Globalvillage Ecosystem': 'GVE',
	Aunite: 'AUNIT',
	Daikicoin: 'DIC',
	LivenPay: 'LVN',
	Rivermount: 'RM',
	'Esports Token': 'EST',
	'Perth Mint Gold Token': 'PMGT',
	MyDexPay: 'XMD',
	'VN Token': 'VN',
	Sapphire: 'SAPP',
	'Rowan Token': 'RWN',
	Consentium: 'CSM',
	'SPIN Protocol': 'SPIN',
	PointPay: 'PXP',
	'Krypton Galaxy Coin': 'KGC',
	CARAT: 'CARAT',
	'WEBN token': 'WEBN',
	NEOBITCOIN: 'NBTC',
	'Ethereum Message Search': 'EMS',
	InnovaMinex: 'MINX',
	'Asian-African Capital Chain': 'ACC',
	Tchain: 'TCH',
	'Mega Lottery Services Global': 'MLR',
	StellarPayGlobal: 'XLPG',
	'Pixie Coin': 'PXC',
	AK12: 'AK12',
	Travel1Click: 'T1C',
	'Bali Coin': 'BALI',
	'Hyper Pay': 'HPY',
	UniDollar: 'UNIUSD',
	Future1coin: 'F1C',
	CelCoin: 'CELC',
	'En-Tan-Mo': 'ETM',
	'Beer Money': 'BEER',
	Kratscoin: 'KTC',
	Flits: 'FLS',
	'OTCBTC Token': 'OTB',
	DWS: 'DWS',
	B91: 'B91',
	Guapcoin: 'GUAP',
	'WHEN Token': 'WHEN',
	LYFE: 'LYFE',
	Mavro: 'MAVRO',
	Chainpay: 'CPAY',
	Alchemy: 'ACOIN',
	'Receive Access Ecosystem': 'RAE',
	LemoChain: 'LEMO',
	'1irstGold': '1GOLD',
	'GoalTime N': 'GTX',
	Volt: 'ACDC',
	'Bitsten Token': 'BST',
	'Falcon Project': 'FNT',
	'Fanaticos Cash': 'FCH',
	'SatoExchange Token': 'SATX',
	'COMSA [XEM]': 'CMS',
	SINERGIA: 'SNG',
	'Bitpanda Ecosystem Token': 'BEST',
	Emanate: 'EMT',
	BitcoinX: 'BCX',
	'The Transfer Token': 'TTT',
	TYCOON69: 'T69',
	LunchMoney: 'LMY',
	'pTokens BTC': 'PBTC',
	BITCOINHEDGE: 'BTCHG',
	'Crex Token': 'CREX',
	'GM Holding': 'GM',
	Becaz: 'BCZ',
	'MGC Token': 'MGC',
	MONNOS: 'MNS',
	BLOCKIDCOIN: 'BID',
	'Simple Software Solutions': 'SSS',
	RAKSUR: 'RAS',
	Sparkster: 'SPRK',
	SoPay: 'SOP',
	'Gric Coin': 'GC',
	'Charg Coin': 'CHG',
	TILWIKI: 'TLW',
	'Commerce Data Connection': 'CDC',
	'The Hustle App': 'HUSL',
	Colletrix: 'CIPX',
	'Experience Token': 'EXT',
	'Game Stars': 'GST',
	'Work Force Coin': 'WFC',
	MORELO: 'MRL',
	Medalte: 'MDTL',
	Mchain: 'MAR',
	'Infinity Esaham': 'INFS',
	BitcoinV: 'BTCV',
	Historia: 'HTA',
	TCOIN: 'TCN',
	'Social Lending Token': 'SLT',
	'Coin Controller Cash': 'CCC',
	"Tutor's Diary": 'TUDA',
	Moozicore: 'MZG',
	ARMTOKEN: 'TARM',
	BlockCDN: 'BCDN',
	XDAG: 'XDAG',
	'Universal Protocol Token': 'UPT',
	'Amun Ether 3x Daily Long': 'ETH3L',
	'Schilling-Coin': 'SCH',
	Bitcoffeen: 'BFF',
	'The global index chain': 'TGIC',
	BuckHathCoin: 'BHIG',
	Newsolution: 'NST',
	'ZCore Token': 'ZCRT',
	USDA: 'USDA',
	'Wallet Plus X': 'WPX',
	QUSD: 'QUSD',
	'Influence Chain': 'INC',
	'AZBI CORE': 'AZBI',
	'First Bitcoin': 'BIT',
	DFOhub: 'BUIDL',
	Altbet: 'ABET',
	UniPower: 'POWER',
	SkyMap: 'SKYM',
	'HeartBout Pay': 'HP',
	Cashhand: 'CHND',
	TerraNova: 'TER',
	Boogle: 'BOO',
	IBStoken: 'IBS',
	VOMER: 'VMR',
	Kryptofranc: 'KYF',
	Defi: 'DEFI',
	'EncryptoTel [ETH]': 'ETT',
	WowSecret: 'WOW',
	Harcomia: 'HCA',
	'ORS Group': 'ORS',
	Coinsto: 'CSO',
	'NSS Coin': 'NSS',
	Cannadrix: 'CND',
	'B ONE PAYMENT': 'B1P',
	Tronipay: 'TRP',
	'COMSA [ETH]': 'CMS',
	SovranoCoin: 'SVR',
	Sombe: 'SBE',
	Endorsit: 'EDS',
	SuperEdge: 'ECT',
	Torex: 'TOR',
	'Lendroid Support Token': 'LST',
	'Wiki Token': 'WIKI',
	Litecash: 'CASH',
	Aeryus: 'AER',
	Voltz: 'VOLTZ',
	Smartup: 'SMARTUP',
	Hanacoin: 'HANA',
	Sierracoin: 'SIERRA',
	'Demeter Chain': 'DMTC',
	Tratok: 'TRAT',
	'Litecoin SV': 'LSV',
	weBloc: 'WOK',
	'Quish Coin': 'QTV',
	Instantily: 'TILY',
	Bitcurate: 'BTCR',
	'Five Star Coin': 'FSC',
	Uranus: 'URAC',
	'MACH Project': 'MACH',
	'Compound USDT': 'CUSDT',
	THENODE: 'THE',
	Kahsh: 'KSH',
	CENTERCOIN: 'CENT',
	PocketNode: 'NODE',
	Korbot: 'KBOT',
	'Jingtum Tech': 'SWTC',
	QPay: 'QPY',
	'Boltt Coin ': 'BOLTT',
	ClubCoin: 'CLUB',
	EXOR: 'EXOR',
	Aerotoken: 'AET',
	'0cash': 'ZCH',
	GermanCoin: 'GCX',
	PlusOneCoin: 'PLUS1',
	'Secure Cash': 'SCSX',
	ROMToken: 'ROM',
	Wallabee: 'WLB',
	'One DEX': 'ODEX',
	'7Eleven': '7E',
	'Blockmason Link': 'BLINK',
	'Maya Preferred 223': 'MAPR',
	MobilinkToken: 'MOLK',
	'Binance GBP Stable Coin': 'BGBP',
	ALA: 'ALA',
	BTCMoon: 'BTCM',
	BOSCore: 'BOS',
	'Small Love Potion': 'SLP',
	'Golden Ratio Token': 'GRT',
	OceanChain: 'OC',
	'Dragon Token': 'DT',
	'Amun Ether 3x Daily Short': 'ETH3S',
	Junsonmingchncoin: 'JMC',
	SEER: 'SEER',
	'cUSD Currency': 'CUSD',
	'Stellar Gold': 'XLMG',
	Tradeplus: 'TDPS',
	EarnBet: 'BET',
	SpectreSecurityCoin: 'XSPC',
	Kemacoin: 'KEMA',
	Valuto: 'VLU',
	'Ladder Network Token': 'LAD',
	'ROS Coin': 'ROS',
	'Bitcoin God': 'GOD',
	WINCOIN: 'WC',
	'PROUD Money': 'PROUD',
	'Destiny Success': 'DXTS',
	SaveNode: 'SNO',
	Centaure: 'CEN',
	StockChain: 'SCC',
	'Global X Change Token': 'GXT',
	HondaisCoin: 'HNDC',
	'QURA GLOBAL': 'QURA',
	ValueChain: 'VLC',
	'Litbinex Coin': 'LTB',
	'CK USD': 'CKUSD',
	RabbitCoin: 'RBBT',
	Quotient: 'XQN',
	Bubble: 'BUB',
	Axiom: 'AXIOM',
	AvatarCoin: 'AV',
	Francs: 'FRN',
	Aces: 'ACES',
	BlazerCoin: 'BLAZR',
	EmberCoin: 'EMB',
	Wink: 'WINK',
	'Moving Cloud Coin': 'MCC',
	MSD: 'MSD',
	'Ethereum Lite': 'ELITE',
	Qube: 'QUBE',
	StarChain: 'STC',
	Maggie: 'MAG',
	Read: 'READ',
	'Animation Vision Cash': 'AVH',
	SalPay: 'SAL',
	CHEX: 'CHEX',
	'IOV BlockChain': 'IOV',
	XTRD: 'XTRD',
	NewsToken: 'NEWOS',
	'CEDEX Coin': 'CEDEX',
	'Obitan Chain': 'OBTC',
	'Hybrid Block': 'HYB',
	KingXChain: 'KXC',
	YUKI: 'YUKI',
	'Usechain Token': 'USE',
	GazeCoin: 'GZE',
	vSportCoin: 'VSC',
	CMITCOIN: 'CMIT',
	CapdaxToken: 'XCD',
	MediBit: 'MEDIBIT',
	'Bgogo Token': 'BGG',
	TOKOK: 'TOK',
	RoboCalls: 'RC20',
	'Big Bang Game Coin': 'BBGC',
	Xtock: 'XTX',
	'OOOBTC TOKEN': 'OBX',
	HUDDL: 'HUDDL',
	UTEMIS: 'UTS',
	BIZKEY: 'BZKY',
	VENJOCOIN: 'VJC',
	'Atlas Token': 'ATLS',
	Muzika: 'MZK',
	'PATHHIVE ': 'PHV',
	'Lucky Block Network': 'LBN',
	'LevelApp Token': 'LVL',
	Alphacon: 'ALP',
	IOU: 'IOUX',
	'Volume Network': 'VOL',
	BitcoinSoV: 'BSOV',
	Electronero: 'ETNX',
	VENA: 'VENA',
	'xCrypt Token': 'XCT',
	LINK: 'LN',
	'City Coin': 'CITY',
	'Oath Protocol': 'OATH',
	'Versess Coin': 'VERS',
	MDtoken: 'MDTK',
	'ALP Coin': 'ALP',
	VERA: 'VERA',
	'Ethlyte Crypto': 'EtLyteT',
	NOVA: 'NOVA',
	'Bitcoin & Company Network': 'BITN',
	RigoBlock: 'GRG',
	NairaX: 'NIRX',
	'HGH Token': 'HGH',
	Creatanium: 'CMB',
	'Apple Network': 'ANK',
	'Global Reserve System': 'GLOB',
	'1AI Token': '1AI',
	FLEX: 'FLEX',
	MEETtoken: 'MTT',
	CitiOs: 'R2R',
	'Compound Dai': 'CDAI',
	'Compound SAI': 'CSAI',
	'Compound USD Coin': 'CUSDC',
	'Asac Coin': 'ASAC',
	SuperSkynet: 'SSN',
	AdsByWiFi: 'WADS',
	SappChain: 'SAPP',
	MyTVchain: 'MYTV',
	'PYRO Network (TRON)': 'PYRO',
	'Pyrrhos Gold': 'PGOLD',
	Hinto: 'HNT',
	Entherfound: 'ETF',
	Metaprediction: 'METP',
	ASYAGRO: 'ASY',
	'United Bull Traders': 'UNB',
	Egas: 'EGAS',
	Bluekey: 'BKY',
	'Compound Ether': 'CETH',
	'KYC.Crypto': 'MIMA',
	'Amun Short Bitcoin Token': 'BTCSHORT',
	'IOOX System': 'IOOX',
	'Amun Bitcoin 3x Daily Long': 'BTC3L',
	'Amun Bitcoin 3x Daily Short': 'BTC3S',
	'Compound Basic Attention Token': 'CBAT',
	'Compound 0x': 'CZRX',
	'Compound Wrapped BTC': 'CWBTC',
	'Compound Augur': 'CREP',
	Nokencoin: 'NOKN',
	'Bankroll Vault': 'VLT',
	'Originate Coin': 'ORC',
	FLUX: 'FLUX',
	'Props Token': 'PROPS',
	BLOCKCLOUT: 'CLOUT',
	'Crypto Cricket Club': '3Cs',
	Sexcoin: 'SXC',
	'Content and AD Network': 'CAN',
	'NAM COIN': 'NAM',
	RRCoin: 'RRC',
	'BiNGO.Fun': '777',
	Zerobank: 'ZB',
	Blacknet: 'BLN',
	Rally: 'RALLY',
	'ESAX Token': 'ESAX',
	'Kappi Network': 'KAPP',
	Lukiu: 'LKU',
	'Know Your Developer': 'KYDC',
	LOLTOKEN: 'LOL',
	Unochain: 'UNOC',
	'Wolfs Group': 'WLF',
	'London Football Exchange': 'LFEC',
	Zelerius: 'ZLS',
	'Ethash Miner': 'HETM',
	'Scopuly Coin': 'SCOP',
	'eToro Pound Sterling': 'GBPX',
	'eToro New Zealand Dollar': 'NZDX',
	'eToro Australian Dollar': 'AUDX',
	'eToro Euro': 'EURX',
	BTCDOWN: 'BTCDOWN',
	'DOCH COIN': 'DCH',
	'mStable USD': 'MUSD',
	'bZx Vesting Token': 'VBZRX',
	'Unit Protocol': 'COL',
}
